/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetRecentQueriesRequest {
    /** The page number for pagination */
    page?: number;
    /** The number of queries per page */
    limit?: number;
    /** Only return queries after this time */
    cutoff_time?: string;
    /** Whether to include assistant responses in the results */
    include_assistant?: boolean;
    /** The start date of the period to retrieve analytics for */
    start_date?: string;
    /** The end date of the period to retrieve analytics for */
    end_date?: string;
}
