# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class LanguageModel(str, enum.Enum):
    CLAUDE_4 = "claude-4-sonnet-20250514"
    COMMAND_A = "command-a-03-2025"

    def visit(self, claude_4: typing.Callable[[], T_Result], command_a: typing.Callable[[], T_Result]) -> T_Result:
        if self is LanguageModel.CLAUDE_4:
            return claude_4()
        if self is LanguageModel.COMMAND_A:
            return command_a()
