/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import * as errors from "../../../../../../../../errors/index.js";
import * as FdrLambda from "../../../../../../../index.js";

export declare namespace Read {
    export interface Options {
        environment?: core.Supplier<environments.FdrLambdaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Read {
    protected readonly _options: Read.Options;

    constructor(_options: Read.Options) {
        this._options = _options;
    }

    /**
     * @param {FdrLambda.docs.v2.read.GetMetadataForUrlRequest} request
     * @param {Read.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FdrLambda.docs.v2.read.DomainNotRegisteredError}
     *
     * @example
     *     await client.docs.v2.read.getDocsUrlMetadata({
     *         url: "url"
     *     })
     */
    public getDocsUrlMetadata(
        request: FdrLambda.docs.v2.read.GetMetadataForUrlRequest,
        requestOptions?: Read.RequestOptions
    ): core.HttpResponsePromise<FdrLambda.docs.v2.read.DocsUrlMetadata> {
        return core.HttpResponsePromise.fromPromise(this.__getDocsUrlMetadata(request, requestOptions));
    }

    private async __getDocsUrlMetadata(
        request: FdrLambda.docs.v2.read.GetMetadataForUrlRequest,
        requestOptions?: Read.RequestOptions
    ): Promise<core.WithRawResponse<FdrLambda.docs.v2.read.DocsUrlMetadata>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/metadata-for-url"
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return {
                data: _response.body as FdrLambda.docs.v2.read.DocsUrlMetadata,
                rawResponse: _response.rawResponse
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as any)?.["error"]) {
                case "DomainNotRegisteredError":
                    throw new FdrLambda.docs.v2.read.DomainNotRegisteredError(_response.rawResponse);
                default:
                    throw new errors.FdrLambdaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FdrLambdaError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FdrLambdaTimeoutError(
                    "Timeout exceeded when calling POST /v2/registry/docs/metadata-for-url."
                );
            case "unknown":
                throw new errors.FdrLambdaError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
