/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface GitHubFileInfoRequest {
    /** The GitHub repository URL (e.g., https://github.com/owner/repo) */
    url: string;
}
