packages:
  - "servers/**"
  - "clis/**"
  - "packages/**"
  - "!packages/**/lib"
  - "!packages/**/dist"
  - "!packages/**/generated"
  - "!packages/**/.next"
  - "!servers/**/lib"
  - "!servers/**/dist"
  - "!servers/**/generated"
  - "!**/__test__/**"

catalog:
  "@next/eslint-plugin-next": "15.5.1-canary.39"
  "@next/bundle-analyzer": "15.5.1-canary.39"
  "@swc/cli": "^0.7.8"
  "@swc/core": "^1.13.5"
  "eslint-config-next": "15.5.1-canary.39"
  "next": "15.5.1-canary.39"
