# This file was auto-generated by Fern from our API Definition.

import glob
import importlib
import os
import types
import typing

import fastapi
import starlette.exceptions
from .core.abstract_fern_service import AbstractFernService
from .core.exceptions import default_exception_handler, fern_http_exception_handler, http_exception_handler
from .core.exceptions.fern_http_exception import FernHTTPException
from .resources.analytics.service.service import AbstractAnalyticsService
from .resources.chat.service.service import AbstractChatService
from .resources.conversations.service.service import AbstractConversationsService
from .resources.document.service.service import AbstractDocumentService
from .resources.guidance.service.service import AbstractGuidanceService
from .resources.index.service.service import AbstractIndexService
from .resources.queries.service.service import AbstractQueriesService
from fastapi import params


def register(
    _app: fastapi.FastAPI,
    *,
    analytics: AbstractAnalyticsService,
    chat: AbstractChatService,
    conversations: AbstractConversationsService,
    document: AbstractDocumentService,
    guidance: AbstractGuidanceService,
    index: AbstractIndexService,
    queries: AbstractQueriesService,
    dependencies: typing.Optional[typing.Sequence[params.Depends]] = None,
) -> None:
    _app.include_router(__register_service(analytics), dependencies=dependencies)
    _app.include_router(__register_service(chat), dependencies=dependencies)
    _app.include_router(__register_service(conversations), dependencies=dependencies)
    _app.include_router(__register_service(document), dependencies=dependencies)
    _app.include_router(__register_service(guidance), dependencies=dependencies)
    _app.include_router(__register_service(index), dependencies=dependencies)
    _app.include_router(__register_service(queries), dependencies=dependencies)

    _app.add_exception_handler(FernHTTPException, fern_http_exception_handler)  # type: ignore
    _app.add_exception_handler(starlette.exceptions.HTTPException, http_exception_handler)  # type: ignore
    _app.add_exception_handler(Exception, default_exception_handler)  # type: ignore


def __register_service(service: AbstractFernService) -> fastapi.APIRouter:
    router = fastapi.APIRouter()
    type(service)._init_fern(router)
    return router


def register_validators(module: types.ModuleType) -> None:
    validators_directory: str = os.path.dirname(module.__file__)  # type: ignore
    for path in glob.glob(os.path.join(validators_directory, "**/*.py"), recursive=True):
        if os.path.isfile(path):
            relative_path = os.path.relpath(path, start=validators_directory)
            module_path = ".".join([module.__name__] + relative_path[:-3].split("/"))
            importlib.import_module(module_path)
