/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         conversation_id: "conversation_id",
 *         query_id: "query_id",
 *         domain: "domain",
 *         is_helpful: true
 *     }
 */
export interface CreateFeedbackRequest {
    /** The ID of the conversation */
    conversation_id: string;
    /** The ID of the query */
    query_id: string;
    /** The domain of the conversation */
    domain: string;
    /** Whether the conversation was helpful */
    is_helpful: boolean;
    /** The feedback message from the user */
    feedback_message?: string;
    /** The email of the user */
    user_email?: string;
}
