/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Settings {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Settings {
    protected readonly _options: Settings.Options;

    constructor(_options: Settings.Options = {}) {
        this._options = _options;
    }

    /**
     * Get settings for a domain and organization.
     *
     * @param {FernAI.GetSettingsRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.getSettings({
     *         domain: "domain"
     *     })
     */
    public getSettings(
        request: FernAI.GetSettingsRequest,
        requestOptions?: Settings.RequestOptions
    ): core.HttpResponsePromise<FernAI.GetSettingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSettings(request, requestOptions));
    }

    private async __getSettings(
        request: FernAI.GetSettingsRequest,
        requestOptions?: Settings.RequestOptions
    ): Promise<core.WithRawResponse<FernAI.GetSettingsResponse>> {
        const { domain } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai"
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetSettingsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling GET /settings/ask-ai.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    /**
     * Toggle Ask AI setting and return job_id for tracking.
     *
     * @param {FernAI.ToggleAskAiRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.toggleAskAi({
     *         domain: "domain",
     *         org_name: "org_name"
     *     })
     */
    public toggleAskAi(
        request: FernAI.ToggleAskAiRequest,
        requestOptions?: Settings.RequestOptions
    ): core.HttpResponsePromise<FernAI.ToggleAskAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__toggleAskAi(request, requestOptions));
    }

    private async __toggleAskAi(
        request: FernAI.ToggleAskAiRequest,
        requestOptions?: Settings.RequestOptions
    ): Promise<core.WithRawResponse<FernAI.ToggleAskAiResponse>> {
        const { domain, org_name: orgName } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        _queryParams["org_name"] = orgName;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/toggle"
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ToggleAskAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /settings/ask-ai/toggle.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    /**
     * Manually trigger reindex for an already enabled Ask AI setup.
     *
     * @param {FernAI.ReindexAskAiRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.reindexAskAi({
     *         domain: "domain",
     *         org_name: "org_name"
     *     })
     */
    public reindexAskAi(
        request: FernAI.ReindexAskAiRequest,
        requestOptions?: Settings.RequestOptions
    ): core.HttpResponsePromise<FernAI.ToggleAskAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__reindexAskAi(request, requestOptions));
    }

    private async __reindexAskAi(
        request: FernAI.ReindexAskAiRequest,
        requestOptions?: Settings.RequestOptions
    ): Promise<core.WithRawResponse<FernAI.ToggleAskAiResponse>> {
        const { domain, org_name: orgName } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        _queryParams["org_name"] = orgName;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/reindex"
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ToggleAskAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /settings/ask-ai/reindex.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    /**
     * Get the status of Ask AI toggle operation.
     *
     * @param {FernAI.GetToggleStatusRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.getToggleStatus({
     *         domain: "domain"
     *     })
     */
    public getToggleStatus(
        request: FernAI.GetToggleStatusRequest,
        requestOptions?: Settings.RequestOptions
    ): core.HttpResponsePromise<FernAI.ToggleStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getToggleStatus(request, requestOptions));
    }

    private async __getToggleStatus(
        request: FernAI.GetToggleStatusRequest,
        requestOptions?: Settings.RequestOptions
    ): Promise<core.WithRawResponse<FernAI.ToggleStatusResponse>> {
        const { domain } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/toggle/status"
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ToggleStatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling GET /settings/ask-ai/toggle/status."
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
