"use client";

import { useParams, useRouter } from "next/navigation";
import React, { useCallback, useMemo, useState } from "react";

import type * as FernNavigation from "@fern-api/fdr-sdk/navigation";
import { type DocsYmlPageEntry, DocsYmlStorage } from "@fern-docs/components";
import { useSidebarClientNavigation } from "@fern-docs/components/sidebar/nodes/SidebarClientNavigationProvider";
import { mdxToHtml } from "@fern-docs/mdx";

import { Auth0OrgName } from "@/app/services/auth0/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useGitHubRepo } from "@/providers/GitHubRepoContext";
import { useMdxState } from "@/providers/MdxStateContext";
import { createMdxFrontmatter } from "@/utils/createMdxFrontmatter";
import { constructEditorSlug } from "@/utils/editor-routing";
import { pageTitleToSlug } from "@/utils/pageTitleToSlug";
import { EncodedDocsUrl } from "@/utils/types";

interface CreateClientPageProps {
  children: React.ReactNode;
  root: FernNavigation.SidebarRootNode | undefined;
}

export function CreateClientPage({ children, root }: CreateClientPageProps) {
  const [isPopoverOpen, setIsPopoverOpen] = useState(false);
  const [pageTitle, setPageTitle] = useState("");
  const [pageSlug, setPageSlug] = useState("");
  const [selectedSection, setSelectedSection] =
    useState<FernNavigation.SectionNode | null>(null);
  const [error, setError] = useState<string>("");
  const [isCreating, setIsCreating] = useState(false);
  const { stageChanges } = useMdxState();
  const { owner, repo, branch } = useGitHubRepo();
  const router = useRouter();
  const params = useParams();

  const { prependClientNode, clientNodes } = useSidebarClientNavigation();

  // Get all sections root section
  const allSections = useMemo(
    () =>
      root?.children?.filter((child) => {
        if (child.type !== "section") return false;
        return true;
      }) || [],
    [root]
  );

  // Set default section on first load
  React.useEffect(() => {
    if (allSections.length > 0 && !selectedSection) {
      setSelectedSection(allSections[0] as FernNavigation.SectionNode);
    }
  }, [allSections, selectedSection]);

  // Auto-generate slug from page title
  const autoGeneratedSlug = useMemo(() => {
    return pageTitle ? pageTitleToSlug(pageTitle) : "";
  }, [pageTitle]);

  // Use custom slug if provided, otherwise use auto-generated
  const finalSlug = pageSlug.trim() || autoGeneratedSlug;

  // Validation function
  const validateForm = useCallback(() => {
    setError("");

    if (!pageTitle.trim()) {
      setError("Page title is required");
      return false;
    }

    if (!selectedSection) {
      setError("Please select a section");
      return false;
    }

    if (!finalSlug) {
      setError("Invalid page title - cannot generate slug");
      return false;
    }

    // Check for duplicate slugs in the selected section
    const existingClientPages = clientNodes?.[selectedSection.id] || [];
    const clientDuplicate = existingClientPages.some(
      (page) => page.slug === finalSlug
    );

    // Also check existing server pages in the selected section
    const existingServerPages =
      selectedSection.children?.filter((child) => child.type === "page") || [];
    const serverDuplicate = existingServerPages.some(
      (page) => page.slug === finalSlug
    );

    if (clientDuplicate || serverDuplicate) {
      setError("A page with this slug already exists in this section");
      return false;
    }

    // Check if slug contains invalid characters
    const validSlugPattern = /^[a-z0-9-]+$/;
    if (!validSlugPattern.test(finalSlug)) {
      setError("Slug can only contain lowercase letters, numbers, and hyphens");
      return false;
    }

    return true;
  }, [pageTitle, selectedSection, finalSlug, clientNodes]);

  const updateDocsYml = useCallback(
    async (sectionTitle: string, pageEntry: DocsYmlPageEntry) => {
      try {
        // First get the current docs.yml content
        const response = await fetch("/api/get-docs-yml", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            owner,
            repo,
            branch,
            orgName: params.orgName,
          }),
        });

        if (!response.ok) {
          const errorText = await response.text();
          console.error(
            "API response error:",
            response.status,
            response.statusText,
            errorText
          );
          throw new Error(
            `Failed to get docs.yml: ${response.status} ${response.statusText} - ${errorText}`
          );
        }

        const { docsYmlContent } = await response.json();

        // Set the base content and add the update
        DocsYmlStorage.setBaseContent(branch, docsYmlContent);
        DocsYmlStorage.addUpdate(branch, sectionTitle, pageEntry);

        return true;
      } catch (error) {
        console.error("Error updating docs.yml:", error);
        return false;
      }
    },
    [owner, repo, branch, params.orgName]
  );

  const handleCreatePage = useCallback(async () => {
    if (!validateForm()) {
      return;
    }

    if (!selectedSection) {
      setError("Please select a section");
      return;
    }

    setIsCreating(true);
    setError("");

    try {
      // Generate MDX frontmatter from user's form input
      // This creates the foundational content for a brand new client page
      const mdx = createMdxFrontmatter({
        title: pageTitle,
        slug: finalSlug,
      });
      const { html, frontmatter, originalElements } = mdxToHtml(mdx);

      // Use the final slug (custom or auto-generated)
      const slug = finalSlug;

      // Create consistent slug construction for both staging and routing
      const fullSlug = selectedSection.slug
        ? `${selectedSection.slug}/${slug}`
        : slug;

      // Stage the changes
      stageChanges(`fern/${fullSlug}.mdx`, {
        html,
        frontmatter,
        originalElements,
      });

      // Close popover and reset form
      setIsPopoverOpen(false);
      setPageTitle("");
      setPageSlug("");
      setError("");
      setSelectedSection(
        allSections.length > 0
          ? (allSections[0] as FernNavigation.SectionNode)
          : null
      );

      // Navigate to the new page using the proper editor routing
      const orgName = params.orgName as Auth0OrgName;
      const docsUrl = params.docsUrl as EncodedDocsUrl;
      const branch = params.branch as string;

      // Use constructEditorSlug to build the proper URL
      const clientPagePath = constructEditorSlug({
        orgName,
        docsUrl,
        branchName: branch,
        slug: fullSlug,
      });

      // Update docs.yml with the new page
      const pageEntry: DocsYmlPageEntry = {
        page: pageTitle,
        path: `${fullSlug}.mdx`,
      };

      const docsYmlUpdateSuccessful = await updateDocsYml(
        selectedSection.title,
        pageEntry
      );

      if (!docsYmlUpdateSuccessful) {
        console.warn("Failed to update docs.yml, but page was created locally");
      }

      // Create a client node for the new page
      const nodeId = `client-${crypto.randomUUID()}` as FernNavigation.NodeId;
      const pageId = `fern/${fullSlug}.mdx` as FernNavigation.PageId;
      const nodeSlug = slug as FernNavigation.Slug;

      const clientNode: FernNavigation.PageNode = {
        type: "page",
        id: nodeId,
        pageId: pageId,
        slug: nodeSlug,
        title: pageTitle,
        canonicalSlug: undefined,
        icon: undefined,
        hidden: undefined,
        authed: undefined,
        viewers: undefined,
        orphaned: undefined,
        featureFlags: undefined,
        noindex: undefined,
      };

      // Cache the client node and the sidebar root node with page data
      prependClientNode?.(
        selectedSection.id,
        clientNode,
        root,
        {
          html,
          frontmatter,
          originalElements,
        },
        fullSlug
      );

      // Navigate to the new page
      router.push(`${clientPagePath}?client-node-id=${clientNode.id}`);
    } catch (err) {
      console.error("Failed to create client page:", err);
      setError(
        err instanceof Error
          ? `Failed to create page: ${err.message}`
          : "Failed to create page. Please try again."
      );
    } finally {
      setIsCreating(false);
    }
  }, [
    validateForm,
    selectedSection,
    pageTitle,
    finalSlug,
    stageChanges,
    prependClientNode,
    root,
    allSections,
    router,
    params,
    updateDocsYml,
  ]);

  return (
    <Popover
      open={isPopoverOpen}
      onOpenChange={(open: boolean) => {
        setIsPopoverOpen(open);
        if (!open) {
          setPageTitle("");
          setPageSlug("");
          setError("");
          setIsCreating(false);
          setSelectedSection(
            allSections.length > 0
              ? (allSections[0] as FernNavigation.SectionNode)
              : null
          );
        }
      }}
    >
      <PopoverTrigger asChild>{children}</PopoverTrigger>
      <PopoverContent className="border-border w-80 border p-3" align="start">
        <div className="space-y-3">
          <div className="space-y-1">
            <label className="text-gray-1100 text-xs font-medium">
              Page title
            </label>
            <Input
              placeholder="Enter page title..."
              value={pageTitle}
              onChange={(e) => {
                setPageTitle(e.target.value);
                setError("");
              }}
              className="w-full text-sm"
              autoFocus
            />
          </div>

          <div className="space-y-1">
            <label className="text-gray-1100 text-xs font-medium">
              Slug{" "}
              <span className="font-normal text-gray-800">
                (auto-generated, optional)
              </span>
            </label>
            <Input
              placeholder={autoGeneratedSlug || "auto-generated-from-title"}
              value={pageSlug}
              onChange={(e) => {
                setPageSlug(e.target.value);
                setError("");
              }}
              className="w-full font-mono text-xs text-gray-800"
            />
          </div>

          <div className="space-y-1">
            <label className="text-gray-1100 text-xs font-medium">
              In section...
            </label>
            {allSections.length === 0 ? (
              <div className="rounded-md border border-gray-200 p-2 text-center text-xs text-gray-800">
                No sections available
              </div>
            ) : (
              <Select
                value={selectedSection?.id || ""}
                onValueChange={(value) => {
                  const section = allSections.find(
                    (s) => (s as FernNavigation.SectionNode).id === value
                  ) as FernNavigation.SectionNode;
                  setSelectedSection(section);
                  setError("");
                }}
              >
                <SelectTrigger className="h-8 w-full text-sm">
                  <SelectValue placeholder="Select section..." />
                </SelectTrigger>
                <SelectContent>
                  {allSections.map((child) => {
                    const section = child as FernNavigation.SectionNode;
                    return (
                      <SelectItem key={section.id} value={section.id}>
                        {getSectionDisplayName(section)}
                      </SelectItem>
                    );
                  })}
                </SelectContent>
              </Select>
            )}
          </div>

          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 p-2 text-xs text-red-700">
              {error}
            </div>
          )}

          <Button
            onClick={handleCreatePage}
            disabled={!pageTitle.trim() || !selectedSection || isCreating}
            className="h-8 w-full cursor-pointer text-sm"
            variant="default"
          >
            {isCreating ? "Creating..." : "Create"}
          </Button>
        </div>
      </PopoverContent>
    </Popover>
  );
}

/**
 * Get the display name for a section (human-readable)
 * @param section - The section node to get the display name for
 * @returns The formatted display name
 */
function getSectionDisplayName(section: FernNavigation.SectionNode): string {
  // Use the title if available, otherwise fall back to a formatted slug
  if (section.title) {
    return section.title;
  }

  // Format slug for display (capitalize and replace dashes/underscores with spaces)
  if (section.slug) {
    return section.slug
      .split(/[-_]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }

  return "Untitled Section";
}
