"use client";

import { useParams } from "next/navigation";
import React, { useCallback, useMemo, useState } from "react";

import { useRouter } from "@bprogress/next/app";

import type * as FernNavigation from "@fern-api/fdr-sdk/navigation";
import {
  NavigationContext,
  UNNAMED_SECTION_DISPLAY_NAMES,
  createMdxFrontmatter,
} from "@fern-docs/components";
import { SectionWithHierarchy, getAllSections } from "@fern-docs/components";
import { mdxToHtml } from "@fern-docs/mdx";

import { Auth0OrgName } from "@/app/services/auth0/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useGitHubRepo } from "@/providers/GitHubRepoContext";
import { useGitPrInfo } from "@/providers/GitPRContext";
import { usePages } from "@/providers/PagesStoreContext";
import { constructEditorSlug } from "@/utils/editor-routing";
import { pageTitleToSlug } from "@/utils/pageTitleToSlug";
import { EncodedDocsUrl } from "@/utils/types";

interface CreateClientPageProps {
  children: React.ReactNode;
  root: FernNavigation.SidebarRootNode | undefined;
  disabled?: boolean;
  navigationContext?: NavigationContext;
}

export function CreateClientPage({
  children,
  root,
  disabled = false,
  navigationContext,
}: CreateClientPageProps) {
  const [isPopoverOpen, setIsPopoverOpen] = useState(false);
  const [pageTitle, setPageTitle] = useState("");
  const [pageSlug, setPageSlug] = useState("");
  const [selectedSection, setSelectedSection] =
    useState<SectionWithHierarchy | null>(null);
  const [error, setError] = useState<string>("");
  const [isCreating, setIsCreating] = useState(false);
  const { owner, repo, branch } = useGitHubRepo();
  const { site } = useGitPrInfo();
  const router = useRouter();
  const params = useParams();

  const { setDocsYmlBaseContent, createPage, clientNodes } = usePages();

  // Get all sections from the navigation tree (including nested ones)
  const allSections = useMemo(
    () => (root?.children ? getAllSections(root.children, [], root.id) : []),
    [root]
  );

  // Set default section on first load
  React.useEffect(() => {
    if (allSections.length > 0 && !selectedSection) {
      setSelectedSection(allSections[0] ?? null);
    }
  }, [allSections, selectedSection]);

  // Auto-generate slug from page title
  const autoGeneratedSlug = useMemo(() => {
    return pageTitle ? pageTitleToSlug(pageTitle) : "";
  }, [pageTitle]);

  // Use custom slug if provided, otherwise use auto-generated
  const finalSlug = pageSlug.trim() || autoGeneratedSlug;

  // Validation function
  const validateForm = useCallback(() => {
    setError("");

    if (!pageTitle.trim()) {
      setError("Page title is required");
      return false;
    }

    if (!selectedSection) {
      setError("Please select a section");
      return false;
    }

    if (!finalSlug) {
      setError("Invalid page title - cannot generate slug");
      return false;
    }

    // Check for duplicate slugs in the selected section
    const existingClientPages = clientNodes?.[selectedSection.id] || [];
    const clientDuplicate = existingClientPages.some(
      (page) => page.slug === finalSlug
    );

    // Also check existing server pages in the selected section
    const existingServerPages =
      selectedSection.children?.filter((child) => child.type === "page") || [];
    const serverDuplicate = existingServerPages.some(
      (page) => page.slug === finalSlug
    );

    if (clientDuplicate || serverDuplicate) {
      setError("A page with this slug already exists in this section");
      return false;
    }

    // Check if slug contains invalid characters
    const validSlugPattern = /^[a-z0-9-]+$/;
    if (!validSlugPattern.test(finalSlug)) {
      setError("Slug can only contain lowercase letters, numbers, and hyphens");
      return false;
    }

    return true;
  }, [pageTitle, selectedSection, finalSlug, clientNodes]);

  const updateDocsYmlBaseContent = useCallback(async () => {
    try {
      // First get the current docs.yml content
      // TODO: we cannot assume that the whole navigation structure lives in one file
      const response = await fetch("/api/get-docs-yml", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          owner,
          repo,
          site,
          branch,
          orgName: params.orgName,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(
          "API response error:",
          response.status,
          response.statusText,
          errorText
        );
        throw new Error(
          `Failed to get docs.yml: ${response.status} ${response.statusText} - ${errorText}`
        );
      }

      const { docsYmlContent } = await response.json();
      setDocsYmlBaseContent(docsYmlContent);

      return true;
    } catch (error) {
      console.error("Error updating docs.yml:", error);
      return false;
    }
  }, [owner, repo, site, branch, params.orgName, setDocsYmlBaseContent]);

  const handleCreatePage = useCallback(async () => {
    if (!validateForm()) {
      return;
    }

    if (!selectedSection) {
      setError("Please select a section");
      return;
    }

    setIsCreating(true);
    setError("");

    try {
      // Generate MDX frontmatter from user's form input
      // This creates the foundational content for a brand new client page
      const mdx = createMdxFrontmatter({
        title: pageTitle,
        slug: finalSlug,
      });
      const { html, frontmatter } = mdxToHtml(mdx);

      // Use the final slug (custom or auto-generated)
      const slug = finalSlug;

      // Create consistent slug construction for both staging and routing
      const fullSlug = selectedSection.slug
        ? `docs/pages/${selectedSection.slug}/${slug}`
        : slug;

      // Close popover and reset form
      setIsPopoverOpen(false);
      setPageTitle("");
      setPageSlug("");
      setError("");
      setSelectedSection(allSections[0] || null);

      // Navigate to the new page using the proper editor routing
      const orgName = params.orgName as Auth0OrgName;
      const docsUrl = params.docsUrl as EncodedDocsUrl;
      const branch = params.branch as string;

      // Ensure docs.yml base content is loaded before creating the page
      // NOTE: the tradeoff is there will be a small delay in the UI when creating a page
      const docsYmlUpdateSuccessful = await updateDocsYmlBaseContent();

      if (!docsYmlUpdateSuccessful) {
        setError("Failed to load docs.yml. Please try again.");
        setIsCreating(false);
        return;
      }

      // Use constructEditorSlug to build the proper URL
      const clientPagePath = constructEditorSlug({
        orgName,
        docsUrl,
        branchName: branch,
        slug: fullSlug,
      });

      // Create a client node for the new page
      const nodeId =
        `client-${finalSlug}-${Date.now()}` as FernNavigation.NodeId;
      const pageId = `${fullSlug}.mdx` as FernNavigation.PageId;

      const clientNode: FernNavigation.PageNode = {
        type: "page",
        id: nodeId,
        pageId,
        slug: slug as FernNavigation.Slug,
        title: pageTitle,
        canonicalSlug: undefined,
        icon: undefined,
        hidden: undefined,
        authed: undefined,
        viewers: undefined,
        orphaned: undefined,
        featureFlags: undefined,
        noindex: undefined,
        availability: undefined,
      };

      // Use the real parent ID for unnamed sections, otherwise use the section ID
      const parentNodeId = selectedSection.realParentId || selectedSection.id;

      try {
        createPage(
          parentNodeId,
          clientNode,
          root,
          {
            html,
            frontmatter,
          },
          fullSlug,
          navigationContext,
          undefined, // initialContent
          // Pass the selected section for proper docs.yml section title
          selectedSection
        );

        // Navigate to the new page
        router.push(`${clientPagePath}?client-node-id=${clientNode.id}`);
      } catch (pageCreationError) {
        console.error("Failed to create page in store:", pageCreationError);
        throw new Error(
          `Failed to create page in navigation: ${
            pageCreationError instanceof Error
              ? pageCreationError.message
              : "Unknown error"
          }`
        );
      }
    } catch (err) {
      console.error("Failed to create client page:", err);
      setError(
        err instanceof Error
          ? `Failed to create page: ${err.message}`
          : "Failed to create page. Please try again."
      );
    } finally {
      setIsCreating(false);
    }
  }, [
    validateForm,
    selectedSection,
    pageTitle,
    finalSlug,
    createPage,
    root,
    allSections,
    router,
    params,
    updateDocsYmlBaseContent,
    navigationContext,
  ]);

  return (
    <Popover
      open={isPopoverOpen && !disabled}
      onOpenChange={(open: boolean) => {
        if (disabled) return;
        setIsPopoverOpen(open);
        if (!open) {
          setPageTitle("");
          setPageSlug("");
          setError("");
          setIsCreating(false);
          setSelectedSection(allSections[0] || null);
        }
      }}
    >
      <PopoverTrigger asChild disabled={disabled}>
        {children}
      </PopoverTrigger>
      <PopoverContent className="border-border w-80 border p-3" align="start">
        <div className="space-y-3">
          <div className="space-y-1">
            <label className="text-gray-1100 text-xs font-medium">
              Page title
            </label>
            <Input
              placeholder="Enter page title..."
              value={pageTitle}
              onChange={(e) => {
                setPageTitle(e.target.value);
                setError("");
              }}
              className="w-full text-sm"
              autoFocus
            />
          </div>

          <div className="space-y-1">
            <label className="text-gray-1100 text-xs font-medium">
              Slug{" "}
              <span className="font-normal text-gray-800">
                (auto-generated, optional)
              </span>
            </label>
            <Input
              placeholder={autoGeneratedSlug || "auto-generated-from-title"}
              value={pageSlug}
              onChange={(e) => {
                setPageSlug(e.target.value);
                setError("");
              }}
              className="w-full font-mono text-xs placeholder:text-gray-800"
            />
          </div>

          <div className="space-y-1">
            <label className="text-gray-1100 text-xs font-medium">
              In section...
            </label>
            {allSections.length === 0 ? (
              <div className="rounded-md border border-gray-200 p-2 text-center text-xs text-gray-800">
                No sections available
              </div>
            ) : (
              <Select
                value={selectedSection?.id || ""}
                onValueChange={(value) => {
                  const section = allSections.find((s) => s.id === value);
                  if (!section) {
                    return;
                  }
                  setSelectedSection(section);
                  setError("");
                }}
              >
                <SelectTrigger className="h-8 w-full text-sm">
                  <SelectValue placeholder="Select section..." />
                </SelectTrigger>
                <SelectContent className="border-border">
                  {allSections.map((section) => {
                    // Filter out generic parent titles like "Root" or "Untitled Section"
                    // that don't provide meaningful hierarchy information
                    const meaningfulParentTitles = section.parentTitles.filter(
                      (title) =>
                        title !== UNNAMED_SECTION_DISPLAY_NAMES.ROOT &&
                        title !== UNNAMED_SECTION_DISPLAY_NAMES.UNNAMED
                    );

                    return (
                      <SelectItem key={section.id} value={section.id}>
                        <div className="flex items-center">
                          {meaningfulParentTitles.length > 0 && (
                            <span className="text-muted-foreground mr-1">
                              {meaningfulParentTitles.join(" / ")} /
                            </span>
                          )}
                          <span
                            className={
                              section.isUnnamed
                                ? "text-muted-foreground"
                                : undefined
                            }
                          >
                            {getSectionDisplayName(section)}
                          </span>
                        </div>
                      </SelectItem>
                    );
                  })}
                </SelectContent>
              </Select>
            )}
          </div>

          {error && (
            <div className="rounded-md border border-red-200 bg-red-50 p-2 text-xs text-red-700">
              {error}
            </div>
          )}

          <Button
            onClick={handleCreatePage}
            disabled={!pageTitle.trim() || !selectedSection || isCreating}
            className="h-8 w-full cursor-pointer text-sm"
            variant="default"
          >
            {isCreating ? "Creating..." : "Create"}
          </Button>
        </div>
      </PopoverContent>
    </Popover>
  );
}

/**
 * Get the display name for a section (human-readable)
 * @param section - The section node to get the display name for
 * @returns The formatted display name
 */
function getSectionDisplayName(section: FernNavigation.SectionNode): string {
  // Use the title if available, otherwise fall back to a formatted slug
  if (section.title) {
    return section.title;
  }

  // Format slug for display (capitalize and replace dashes/underscores with spaces)
  if (section.slug) {
    return section.slug
      .split(/[-_]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }

  return UNNAMED_SECTION_DISPLAY_NAMES.UNNAMED;
}
