/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class FernFaiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, FernFaiTimeoutError.prototype);
    }
}
