# This file was auto-generated by Fern from our API Definition.

import abc
import datetime as dt
import functools
import inspect
import logging
import typing

import fastapi
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ...commons.errors.bad_request_error import BadRequestError
from ...commons.errors.internal_error import InternalError
from ..types.group_by import GroupBy
from ..types.histogram_analytics import HistogramAnalytics
from ..types.insights import Insights


class AbstractAnalyticsService(AbstractFernService):
    """
    AbstractAnalyticsService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def get_histogram_analytics(
        self,
        *,
        domain: str,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        group_by: GroupBy,
    ) -> HistogramAnalytics:
        """
        Retrieve the usage histogram analytics for a given period
        """
        ...

    @abc.abstractmethod
    def get_insights(
        self,
        *,
        domain: str,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
    ) -> Insights:
        """
        Retrieve the insights for a given period
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_get_histogram_analytics(router=router)
        cls.__init_get_insights(router=router)

    @classmethod
    def __init_get_histogram_analytics(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_histogram_analytics)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "start_date":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=None, description="The start date of the period to retrieve analytics for"
                        )
                    )
                )
            elif parameter_name == "end_date":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=None, description="The end date of the period to retrieve analytics for"
                        )
                    )
                )
            elif parameter_name == "group_by":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=..., alias="groupBy", description="The field to group the analytics by"
                        )
                    )
                )
            else:
                new_parameters.append(parameter)
        setattr(cls.get_histogram_analytics, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_histogram_analytics)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> HistogramAnalytics:
            try:
                return cls.get_histogram_analytics(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_histogram_analytics' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_histogram_analytics.__globals__)

        router.get(
            path="/analytics/histogram/{domain}",
            response_model=HistogramAnalytics,
            description=AbstractAnalyticsService.get_histogram_analytics.__doc__,
            **get_route_args(cls.get_histogram_analytics, default_tag="analytics"),
        )(wrapper)

    @classmethod
    def __init_get_insights(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_insights)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "start_date":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=None, description="The start date of the period to retrieve analytics for"
                        )
                    )
                )
            elif parameter_name == "end_date":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=None, description="The end date of the period to retrieve analytics for"
                        )
                    )
                )
            else:
                new_parameters.append(parameter)
        setattr(cls.get_insights, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_insights)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Insights:
            try:
                return cls.get_insights(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_insights' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_insights.__globals__)

        router.get(
            path="/analytics/insights/{domain}",
            response_model=Insights,
            description=AbstractAnalyticsService.get_insights.__doc__,
            **get_route_args(cls.get_insights, default_tag="analytics"),
        )(wrapper)
