/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Conversation {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Conversation {
    protected readonly _options: Conversation.Options;

    constructor(_options: Conversation.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {string} domain
     * @param {string} conversationId
     * @param {Conversation.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.conversation.getConversationById("domain", "conversation_id")
     */
    public getConversationById(
        domain: string,
        conversationId: string,
        requestOptions?: Conversation.RequestOptions,
    ): core.HttpResponsePromise<FernAI.GetConversationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getConversationById(domain, conversationId, requestOptions));
    }

    private async __getConversationById(
        domain: string,
        conversationId: string,
        requestOptions?: Conversation.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.GetConversationResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `conversation/${encodeURIComponent(domain)}/${encodeURIComponent(conversationId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetConversationResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling GET /conversation/{domain}/{conversation_id}.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
