/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetAnalyticsInsightsRequest {
    /** The start date of the period to retrieve analytics for */
    start_date?: string;
    /** The end date of the period to retrieve analytics for */
    end_date?: string;
}
