/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         start_date: "2024-01-15T09:30:00Z",
 *         end_date: "2024-01-15T09:30:00Z"
 *     }
 */
export interface GetInsightsRequest {
    /**
     * The start date of the period to retrieve analytics for
     */
    start_date: string;
    /**
     * The end date of the period to retrieve analytics for
     */
    end_date: string;
}
