/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as core from "../../../../../../core/index.js";
import type * as environments from "../../../../../../environments.js";
import { Read } from "../resources/read/client/Client.js";

export declare namespace V2 {
    export interface Options {
        environment?: core.Supplier<environments.FdrLambdaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class V2 {
    protected readonly _options: V2.Options;
    protected _read: Read | undefined;

    constructor(_options: V2.Options) {
        this._options = _options;
    }

    public get read(): Read {
        return (this._read ??= new Read(this._options));
    }
}
