/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Query {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Query {
    protected readonly _options: Query.Options;

    constructor(_options: Query.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {FernAI.CreateQueryRequest} request
     * @param {Query.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.query.createQuery({
     *         domain: "domain",
     *         body: {
     *             query_id: "query_id",
     *             conversation_id: "conversation_id",
     *             domain: "domain",
     *             text: "text",
     *             role: "role",
     *             source: "source",
     *             created_at: "2024-01-15T09:30:00Z"
     *         }
     *     })
     */
    public createQuery(
        request: FernAI.CreateQueryRequest,
        requestOptions?: Query.RequestOptions
    ): core.HttpResponsePromise<FernAI.CreateQueryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createQuery(request, requestOptions));
    }

    private async __createQuery(
        request: FernAI.CreateQueryRequest,
        requestOptions?: Query.RequestOptions
    ): Promise<core.WithRawResponse<FernAI.CreateQueryResponse>> {
        const { domain, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "queries"
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.CreateQueryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /queries.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    /**
     * @param {string} domain
     * @param {FernAI.GetRecentQueriesRequest} request
     * @param {Query.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.query.getRecentQueries("domain")
     */
    public getRecentQueries(
        domain: string,
        request: FernAI.GetRecentQueriesRequest = {},
        requestOptions?: Query.RequestOptions
    ): core.HttpResponsePromise<FernAI.GetQueriesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getRecentQueries(domain, request, requestOptions));
    }

    private async __getRecentQueries(
        domain: string,
        request: FernAI.GetRecentQueriesRequest = {},
        requestOptions?: Query.RequestOptions
    ): Promise<core.WithRawResponse<FernAI.GetQueriesResponse>> {
        const {
            page,
            limit,
            cutoff_time: cutoffTime,
            include_assistant: includeAssistant,
            start_date: startDate,
            end_date: endDate
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        if (cutoffTime != null) {
            _queryParams["cutoff_time"] = cutoffTime;
        }

        if (includeAssistant != null) {
            _queryParams["include_assistant"] = includeAssistant.toString();
        }

        if (startDate != null) {
            _queryParams["start_date"] = startDate;
        }

        if (endDate != null) {
            _queryParams["end_date"] = endDate;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `queries/${encodeURIComponent(domain)}`
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetQueriesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling GET /queries/{domain}.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
