# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HistogramAnalyticsBar(UniversalBaseModel):
    label: str
    query_count: int = pydantic.Field(alias="queryCount")
    conversation_count: int = pydantic.Field(alias="conversationCount")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
