# This file was auto-generated by Fern from our API Definition.

import abc
import functools
import inspect
import logging
import typing

import fastapi
import starlette
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ...commons.errors.bad_request_error import BadRequestError
from ...commons.errors.internal_error import InternalError
from ..types.document import Document
from ..types.document_id_response import DocumentIdResponse
from ..types.document_list import DocumentList
from .index_document_request import IndexDocumentRequest
from .update_document_request import UpdateDocumentRequest


class AbstractDocumentService(AbstractFernService):
    """
    AbstractDocumentService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def create_document(self, *, body: IndexDocumentRequest, domain: str) -> DocumentIdResponse:
        """
        Index a document for a given domain. Documents can be used to provide additional context to Ask Fern and improve its accuracy.
        """
        ...

    @abc.abstractmethod
    def update_document(self, *, body: UpdateDocumentRequest, domain: str, document_id: str) -> Document:
        """
        Update a document for a given domain
        """
        ...

    @abc.abstractmethod
    def delete_document_by_id(self, *, domain: str, document_id: str) -> None:
        """
        Delete a document for a given domain
        """
        ...

    @abc.abstractmethod
    def get_document_by_id(self, *, domain: str, document_id: str) -> Document:
        """
        Get a document for a given domain
        """
        ...

    @abc.abstractmethod
    def get_documents(
        self, *, domain: str, page: typing.Optional[int] = None, limit: typing.Optional[int] = None
    ) -> DocumentList:
        """
        Retrieve all paginated documents for a given domain
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_create_document(router=router)
        cls.__init_update_document(router=router)
        cls.__init_delete_document_by_id(router=router)
        cls.__init_get_document_by_id(router=router)
        cls.__init_get_documents(router=router)

    @classmethod
    def __init_create_document(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.create_document)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.create_document, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.create_document)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> DocumentIdResponse:
            try:
                return cls.create_document(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'create_document' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.create_document.__globals__)

        router.post(
            path="/document/{domain}/create",
            response_model=DocumentIdResponse,
            description=AbstractDocumentService.create_document.__doc__,
            **get_route_args(cls.create_document, default_tag="document"),
        )(wrapper)

    @classmethod
    def __init_update_document(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.update_document)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "document_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.update_document, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.update_document)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Document:
            try:
                return cls.update_document(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'update_document' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.update_document.__globals__)

        router.patch(
            path="/document/{domain}/{document_id}",
            response_model=Document,
            description=AbstractDocumentService.update_document.__doc__,
            **get_route_args(cls.update_document, default_tag="document"),
        )(wrapper)

    @classmethod
    def __init_delete_document_by_id(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.delete_document_by_id)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "document_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.delete_document_by_id, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.delete_document_by_id)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> None:
            try:
                return cls.delete_document_by_id(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'delete_document_by_id' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.delete_document_by_id.__globals__)

        router.delete(
            path="/document/{domain}/{document_id}",
            response_model=None,
            status_code=starlette.status.HTTP_204_NO_CONTENT,
            description=AbstractDocumentService.delete_document_by_id.__doc__,
            **get_route_args(cls.delete_document_by_id, default_tag="document"),
        )(wrapper)

    @classmethod
    def __init_get_document_by_id(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_document_by_id)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "document_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.get_document_by_id, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_document_by_id)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Document:
            try:
                return cls.get_document_by_id(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_document_by_id' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_document_by_id.__globals__)

        router.get(
            path="/document/{domain}/{document_id}",
            response_model=Document,
            description=AbstractDocumentService.get_document_by_id.__doc__,
            **get_route_args(cls.get_document_by_id, default_tag="document"),
        )(wrapper)

    @classmethod
    def __init_get_documents(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_documents)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "page":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            elif parameter_name == "limit":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            else:
                new_parameters.append(parameter)
        setattr(cls.get_documents, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_documents)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> DocumentList:
            try:
                return cls.get_documents(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_documents' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_documents.__globals__)

        router.get(
            path="/document/{domain}",
            response_model=DocumentList,
            description=AbstractDocumentService.get_documents.__doc__,
            **get_route_args(cls.get_documents, default_tag="document"),
        )(wrapper)
