# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateDocumentRequest(UniversalBaseModel):
    document: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated content of the document that will be returned to Ask Fern during document retrieval.
    If not provided, this field will remain unchanged.
    """

    chunk: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated textual content that should be vectorized when indexing the document.
    If not provided, this field will remain unchanged.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated title of the document. If not provided, this field will remain unchanged.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated url of the document. If not provided, this field will remain unchanged.
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated version of the document. If not provided, this field will remain unchanged.
    """

    product: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated product of the document. If not provided, this field will remain unchanged.
    """

    keywords: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The updated keywords of the document. If not provided, this field will remain unchanged.
    """

    authed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    The updated authed status of the document. If not provided, this field will remain unchanged.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
