"""Make the created_time column autopopulate

Revision ID: 11b67866ecc7
Revises: 3d785ee51ca7
Create Date: 2025-10-10 15:18:26.019055

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "11b67866ecc7"
down_revision: Union[str, Sequence[str], None] = "3d785ee51ca7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, populate existing null values with current timestamp
    op.execute("UPDATE settings SET created_time = NOW() WHERE created_time IS NULL")

    # Then set the column as non-nullable with a default
    op.alter_column(
        "settings",
        "created_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        server_default=sa.text("NOW()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("settings", "created_time", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###
