"""Add platform enablement flags for settings

Revision ID: 2aa05c51edf0
Revises: 
Create Date: 2025-10-06 10:36:51.646070

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2aa05c51edf0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_message_classification",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("message_ts", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_slack_message_classification_classification",
        "slack_message_classification",
        ["classification"],
        unique=False,
    )
    op.create_index(
        "idx_slack_message_classification_classified_at",
        "slack_message_classification",
        ["classified_at"],
        unique=False,
    )
    op.create_index(
        "idx_slack_message_classification_team_ts",
        "slack_message_classification",
        ["team_id", "message_ts"],
        unique=False,
    )
    op.add_column("settings", sa.Column("docs_enabled", sa.Boolean(), nullable=False, server_default="true"))
    op.add_column("settings", sa.Column("slack_enabled", sa.Boolean(), nullable=False, server_default="true"))
    op.add_column("settings", sa.Column("discord_enabled", sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "discord_enabled")
    op.drop_column("settings", "slack_enabled")
    op.drop_column("settings", "docs_enabled")
    op.drop_index("idx_slack_message_classification_team_ts", table_name="slack_message_classification")
    op.drop_index("idx_slack_message_classification_classified_at", table_name="slack_message_classification")
    op.drop_index("idx_slack_message_classification_classification", table_name="slack_message_classification")
    op.drop_table("slack_message_classification")
    # ### end Alembic commands ###
