"""Add created_time and is_preview to settings table

Revision ID: 3d785ee51ca7
Revises: 2aa05c51edf0
Create Date: 2025-10-10 15:12:34.073749

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d785ee51ca7"
down_revision: Union[str, Sequence[str], None] = "2aa05c51edf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_queries_query_id"), table_name="queries")
    op.add_column("settings", sa.Column("created_time", sa.DateTime(), nullable=True))
    # Add is_preview as nullable first, set default values, then make it non-nullable
    op.add_column("settings", sa.Column("is_preview", sa.Boolean(), nullable=True))
    op.execute("UPDATE settings SET is_preview = FALSE WHERE is_preview IS NULL")
    op.alter_column("settings", "is_preview", nullable=False, server_default=sa.text("false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "is_preview")
    op.drop_column("settings", "created_time")
    op.create_index(op.f("ix_queries_query_id"), "queries", ["query_id"], unique=False)
    # ### end Alembic commands ###
