/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         index_name: "index_name"
 *     }
 */
export interface SyncIndexRequest {
    /** The name of the index to sync */
    index_name: string;
}
