/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Index {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Index {
    protected readonly _options: Index.Options;

    constructor(_options: Index.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {string} domain
     * @param {Index.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.index.reconstructQueryIndex("domain")
     */
    public reconstructQueryIndex(
        domain: string,
        requestOptions?: Index.RequestOptions,
    ): core.HttpResponsePromise<FernAI.ReconstructIndexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__reconstructQueryIndex(domain, requestOptions));
    }

    private async __reconstructQueryIndex(
        domain: string,
        requestOptions?: Index.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.ReconstructIndexResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `index/${encodeURIComponent(domain)}/reconstruct`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ReconstructIndexResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /index/{domain}/reconstruct.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {FernAI.SyncIndexRequest} request
     * @param {Index.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.index.syncIndexToQueryIndex("domain", {
     *         index_name: "index_name"
     *     })
     */
    public syncIndexToQueryIndex(
        domain: string,
        request: FernAI.SyncIndexRequest,
        requestOptions?: Index.RequestOptions,
    ): core.HttpResponsePromise<FernAI.SyncIndexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__syncIndexToQueryIndex(domain, request, requestOptions));
    }

    private async __syncIndexToQueryIndex(
        domain: string,
        request: FernAI.SyncIndexRequest,
        requestOptions?: Index.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.SyncIndexResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `index/${encodeURIComponent(domain)}/sync`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.SyncIndexResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /index/{domain}/sync.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
