/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Document {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Document {
    protected readonly _options: Document.Options;

    constructor(_options: Document.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {string} domain
     * @param {FernAI.CreateDocumentRequest} request
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.createDocument("domain", {
     *         document: "document"
     *     })
     */
    public createDocument(
        domain: string,
        request: FernAI.CreateDocumentRequest,
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.CreateDocumentResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__createDocument(domain, request, requestOptions));
    }

    private async __createDocument(
        domain: string,
        request: FernAI.CreateDocumentRequest,
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.CreateDocumentResponse[]>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/create`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.CreateDocumentResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /document/{domain}/create.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {FernAI.CreateDocumentRequest[]} request
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.batchCreateDocument("domain", [{
     *             document: "document"
     *         }])
     */
    public batchCreateDocument(
        domain: string,
        request: FernAI.CreateDocumentRequest[],
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.CreateDocumentResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__batchCreateDocument(domain, request, requestOptions));
    }

    private async __batchCreateDocument(
        domain: string,
        request: FernAI.CreateDocumentRequest[],
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.CreateDocumentResponse[]>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/batch-create`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.CreateDocumentResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /document/{domain}/batch-create.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {string} documentId
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.getDocumentById("domain", "document_id")
     */
    public getDocumentById(
        domain: string,
        documentId: string,
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.GetDocumentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getDocumentById(domain, documentId, requestOptions));
    }

    private async __getDocumentById(
        domain: string,
        documentId: string,
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.GetDocumentResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/${encodeURIComponent(documentId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetDocumentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling GET /document/{domain}/{document_id}.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {string} documentId
     * @param {FernAI.UpdateDocumentRequest} request
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.updateDocument("domain", "document_id")
     */
    public updateDocument(
        domain: string,
        documentId: string,
        request: FernAI.UpdateDocumentRequest = {},
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.UpdateDocumentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateDocument(domain, documentId, request, requestOptions));
    }

    private async __updateDocument(
        domain: string,
        documentId: string,
        request: FernAI.UpdateDocumentRequest = {},
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.UpdateDocumentResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/${encodeURIComponent(documentId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.UpdateDocumentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling PATCH /document/{domain}/{document_id}.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {FernAI.DeleteDocumentRequest} request
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.deleteDocumentById("domain", {
     *         document_id: "document_id"
     *     })
     */
    public deleteDocumentById(
        domain: string,
        request: FernAI.DeleteDocumentRequest,
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.DeleteDocumentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDocumentById(domain, request, requestOptions));
    }

    private async __deleteDocumentById(
        domain: string,
        request: FernAI.DeleteDocumentRequest,
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.DeleteDocumentResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/delete`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.DeleteDocumentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling DELETE /document/{domain}/delete.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {FernAI.DeleteDocumentRequest[]} request
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.batchDeleteDocument("domain", [{
     *             document_id: "document_id"
     *         }])
     */
    public batchDeleteDocument(
        domain: string,
        request: FernAI.DeleteDocumentRequest[],
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.DeleteDocumentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__batchDeleteDocument(domain, request, requestOptions));
    }

    private async __batchDeleteDocument(
        domain: string,
        request: FernAI.DeleteDocumentRequest[],
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.DeleteDocumentResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/batch-delete`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.DeleteDocumentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling DELETE /document/{domain}/batch-delete.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {FernAI.GetDocumentsRequest} request
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.getDocuments("domain")
     */
    public getDocuments(
        domain: string,
        request: FernAI.GetDocumentsRequest = {},
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.GetDocumentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getDocuments(domain, request, requestOptions));
    }

    private async __getDocuments(
        domain: string,
        request: FernAI.GetDocumentsRequest = {},
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.GetDocumentsResponse>> {
        const { page, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams["page"] = page.toString();
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetDocumentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling GET /document/{domain}.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} domain
     * @param {Document.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.document.deleteAllDocuments("domain")
     */
    public deleteAllDocuments(
        domain: string,
        requestOptions?: Document.RequestOptions,
    ): core.HttpResponsePromise<FernAI.DeleteDocumentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAllDocuments(domain, requestOptions));
    }

    private async __deleteAllDocuments(
        domain: string,
        requestOptions?: Document.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.DeleteDocumentResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `document/${encodeURIComponent(domain)}/delete-all`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.DeleteDocumentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling DELETE /document/{domain}/delete-all.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
