import React from "react";

import { Prose } from "@fern-docs/components/mdx/prose";

import { FernAnchor } from "@/docs/components/FernAnchor";

export const ParamField: React.FC<
  React.PropsWithChildren<{
    type: string;
    default?: string;
    required?: boolean;
    deprecated?: boolean;
    toc?: boolean;
    /** id generated by rehype-slug plugin */
    id?: string;
    /** title generated by rehype-param-field plugin */
    title?: string;
    /** @deprecated unused Mintlify prop */
    initialValue?: any;
    /** @deprecated unused Mintlify prop */
    placeholder?: string;
  }> &
    (
      | { query: string }
      | { path: string }
      | { body: string }
      | { header: string }
    )
> = ({
  type,
  default: defaultProp,
  required,
  deprecated,
  toc,
  children,
  id,
  title,
  ...props
}) => {
  // use title prop if available, otherwise fall back to extracting from props
  const name =
    title ||
    ("query" in props
      ? props.query
      : "path" in props
        ? props.path
        : "body" in props
          ? props.body
          : props.header);

  return (
    <div className="fern-api-property border-border-default border-b">
      <div className="fern-api-property-header">
        {toc ? (
          <FernAnchor href={`#${id}`} asChild>
            <h6 className="fern-api-property-key" id={id}>
              {name}
            </h6>
          </FernAnchor>
        ) : (
          <div className="fern-api-property-key">{name}</div>
        )}
        <div className="fern-api-property-meta">
          <span>{type}</span>
          {defaultProp && <span>Defaults to {defaultProp}</span>}
          {deprecated && (
            <span className="text-(color:--amber-a11)">Deprecated</span>
          )}
          {required && <span className="text-(color:--red-a11)">Required</span>}
        </div>
      </div>
      {children && <Prose size="sm">{children}</Prose>}
    </div>
  );
};
