/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateGuidanceRequest {
    /** The updated context of the guidance document, as a list of strings, that will be indexed. If not provided, this field will remain unchanged. */
    context?: string[];
    /** The updated content of the guidance document that will be returned to Ask Fern during Ask Fern retrieval. If not provided, this field will remain unchanged. */
    document?: string;
}
