/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         query_id: "query_id",
 *         conversation_id: "conversation_id",
 *         domain: "domain",
 *         text: "text",
 *         role: "role",
 *         source: "source",
 *         created_at: "2024-01-15T09:30:00Z",
 *         time_to_first_token: undefined
 *     }
 */
export interface CreateQueryRequest {
    query_id: string;
    conversation_id: string;
    domain: string;
    text: string;
    role: string;
    source: string;
    created_at: string;
    /** Time in seconds until first token was received. Only specified for Assistant responses. */
    time_to_first_token?: number;
}
