/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Analytics } from "./api/resources/analytics/client/Client.js";
import { Chat } from "./api/resources/chat/client/Client.js";
import { Conversation } from "./api/resources/conversation/client/Client.js";
import { Document } from "./api/resources/document/client/Client.js";
import { Feedback } from "./api/resources/feedback/client/Client.js";
import { Github } from "./api/resources/github/client/Client.js";
import { Guidance } from "./api/resources/guidance/client/Client.js";
import { Health } from "./api/resources/health/client/Client.js";
import { Index } from "./api/resources/index/client/Client.js";
import { Mcp } from "./api/resources/mcp/client/Client.js";
import { Query } from "./api/resources/query/client/Client.js";
import { Settings } from "./api/resources/settings/client/Client.js";

export declare namespace FernAIClient {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class FernAIClient {
    protected readonly _options: FernAIClient.Options;
    protected _analytics: Analytics | undefined;
    protected _chat: Chat | undefined;
    protected _conversation: Conversation | undefined;
    protected _document: Document | undefined;
    protected _feedback: Feedback | undefined;
    protected _github: Github | undefined;
    protected _guidance: Guidance | undefined;
    protected _health: Health | undefined;
    protected _index: Index | undefined;
    protected _mcp: Mcp | undefined;
    protected _query: Query | undefined;
    protected _settings: Settings | undefined;

    constructor(_options: FernAIClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get analytics(): Analytics {
        return (this._analytics ??= new Analytics(this._options));
    }

    public get chat(): Chat {
        return (this._chat ??= new Chat(this._options));
    }

    public get conversation(): Conversation {
        return (this._conversation ??= new Conversation(this._options));
    }

    public get document(): Document {
        return (this._document ??= new Document(this._options));
    }

    public get feedback(): Feedback {
        return (this._feedback ??= new Feedback(this._options));
    }

    public get github(): Github {
        return (this._github ??= new Github(this._options));
    }

    public get guidance(): Guidance {
        return (this._guidance ??= new Guidance(this._options));
    }

    public get health(): Health {
        return (this._health ??= new Health(this._options));
    }

    public get index(): Index {
        return (this._index ??= new Index(this._options));
    }

    public get mcp(): Mcp {
        return (this._mcp ??= new Mcp(this._options));
    }

    public get query(): Query {
        return (this._query ??= new Query(this._options));
    }

    public get settings(): Settings {
        return (this._settings ??= new Settings(this._options));
    }
}
