/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Analytics } from "./api/resources/analytics/client/Client.js";
import { Chat } from "./api/resources/chat/client/Client.js";
import { Conversations } from "./api/resources/conversations/client/Client.js";
import { Document } from "./api/resources/document/client/Client.js";
import { Guidance } from "./api/resources/guidance/client/Client.js";
import { Index } from "./api/resources/index/client/Client.js";
import { Queries } from "./api/resources/queries/client/Client.js";

export declare namespace FernFaiClient {
    export interface Options {
        environment?: core.Supplier<environments.FernFaiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class FernFaiClient {
    protected readonly _options: FernFaiClient.Options;
    protected _analytics: Analytics | undefined;
    protected _chat: Chat | undefined;
    protected _conversations: Conversations | undefined;
    protected _document: Document | undefined;
    protected _guidance: Guidance | undefined;
    protected _index: Index | undefined;
    protected _queries: Queries | undefined;

    constructor(_options: FernFaiClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@fern-api/fai-sdk",
                    "X-Fern-SDK-Version": "0.0.81",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get analytics(): Analytics {
        return (this._analytics ??= new Analytics(this._options));
    }

    public get chat(): Chat {
        return (this._chat ??= new Chat(this._options));
    }

    public get conversations(): Conversations {
        return (this._conversations ??= new Conversations(this._options));
    }

    public get document(): Document {
        return (this._document ??= new Document(this._options));
    }

    public get guidance(): Guidance {
        return (this._guidance ??= new Guidance(this._options));
    }

    public get index(): Index {
        return (this._index ??= new Index(this._options));
    }

    public get queries(): Queries {
        return (this._queries ??= new Queries(this._options));
    }
}
