/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FernFaiEnvironment = {
    Prod: "https://fai.buildwithfern.com",
} as const;

export type FernFaiEnvironment = typeof FernFaiEnvironment.Prod;
