/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FernAIEnvironment = {
    Production: "https://fai.buildwithfern.com",
    Development: "https://fai-dev.buildwithfern.com",
    Local: "http://localhost:8080",
} as const;

export type FernAIEnvironment =
    | typeof FernAIEnvironment.Production
    | typeof FernAIEnvironment.Development
    | typeof FernAIEnvironment.Local;
