/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Document {
    document_id: string;
    chunk: string;
    domain: string;
    document: string;
    title?: string;
    url?: string;
    version?: string;
    product?: string;
    keywords?: string[];
    authed?: boolean;
    created_at: string;
    updated_at: string;
}
