/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernFai from "../../../index.js";

export interface DocumentList {
    documents: FernFai.Document[];
    pagination: FernFai.Pagination;
}
