/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index.js";
import * as core from "../../../../core/index.js";

export class InternalError extends errors.FernFaiError {
    constructor(body: string, rawResponse?: core.RawResponse) {
        super({
            message: "InternalError",
            statusCode: 401,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, InternalError.prototype);
    }
}
