/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Query {
    query_id: string;
    conversation_id: string;
    domain: string;
    text: string;
    role: string;
    source: string;
    created_at: string;
    time_to_first_token?: number;
}
