/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Analytics", () => {
    test("getHistogramAnalytics", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bars: [
                { label: "label", queryCount: 1, conversationCount: 1 },
                { label: "label", queryCount: 1, conversationCount: 1 },
            ],
        };
        server
            .mockEndpoint()
            .get("/analytics/histogram/domain")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.analytics.getHistogramAnalytics("domain", {
            start_date: "2024-01-15T09:30:00Z",
            end_date: "2024-01-15T09:30:00Z",
            groupBy: "DAY",
        });
        expect(response).toEqual({
            bars: [
                {
                    label: "label",
                    queryCount: 1,
                    conversationCount: 1,
                },
                {
                    label: "label",
                    queryCount: 1,
                    conversationCount: 1,
                },
            ],
        });
    });

    test("getInsights", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            insights: [
                { insightText: "insightText", numberOfQueries: 1, examples: ["examples", "examples"] },
                { insightText: "insightText", numberOfQueries: 1, examples: ["examples", "examples"] },
            ],
        };
        server
            .mockEndpoint()
            .get("/analytics/insights/domain")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.analytics.getInsights("domain", {
            start_date: "2024-01-15T09:30:00Z",
            end_date: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual({
            insights: [
                {
                    insightText: "insightText",
                    numberOfQueries: 1,
                    examples: ["examples", "examples"],
                },
                {
                    insightText: "insightText",
                    numberOfQueries: 1,
                    examples: ["examples", "examples"],
                },
            ],
        });
    });
});
