/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Chat", () => {
    test("chatCompletion", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: undefined,
            system_prompt: undefined,
            messages: [
                { role: "role", content: "content" },
                { role: "role", content: "content" },
            ],
        };
        const rawResponseBody = [
            { role: "role", content: "content" },
            { role: "role", content: "content" },
        ];
        server
            .mockEndpoint()
            .post("/chat/domain")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.chatCompletion("domain", {
            model: undefined,
            system_prompt: undefined,
            messages: [
                {
                    role: "role",
                    content: "content",
                },
                {
                    role: "role",
                    content: "content",
                },
            ],
        });
        expect(response).toEqual([
            {
                role: "role",
                content: "content",
            },
            {
                role: "role",
                content: "content",
            },
        ]);
    });
});
