/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Conversations", () => {
    test("getConversation", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            conversation_id: "conversation_id",
            created_at: "2024-01-15T09:30:00Z",
            turns: [
                { role: "role", text: "text", created_at: "2024-01-15T09:30:00Z" },
                { role: "role", text: "text", created_at: "2024-01-15T09:30:00Z" },
            ],
        };
        server
            .mockEndpoint()
            .get("/conversations/domain/conversation_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversations.getConversation("domain", "conversation_id");
        expect(response).toEqual({
            conversation_id: "conversation_id",
            created_at: "2024-01-15T09:30:00Z",
            turns: [
                {
                    role: "role",
                    text: "text",
                    created_at: "2024-01-15T09:30:00Z",
                },
                {
                    role: "role",
                    text: "text",
                    created_at: "2024-01-15T09:30:00Z",
                },
            ],
        });
    });
});
