/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Document", () => {
    test("createDocument", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            document: "document",
            chunk: undefined,
            title: undefined,
            url: undefined,
            version: undefined,
            product: undefined,
            keywords: undefined,
            authed: undefined,
        };
        const rawResponseBody = { document_id: "document_id" };
        server
            .mockEndpoint()
            .post("/document/domain/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.document.createDocument("domain", {
            document: "document",
            chunk: undefined,
            title: undefined,
            url: undefined,
            version: undefined,
            product: undefined,
            keywords: undefined,
            authed: undefined,
        });
        expect(response).toEqual({
            document_id: "document_id",
        });
    });

    test("updateDocument", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            document: undefined,
            chunk: undefined,
            title: undefined,
            url: undefined,
            version: undefined,
            product: undefined,
            keywords: undefined,
            authed: undefined,
        };
        const rawResponseBody = {
            document_id: "document_id",
            chunk: "chunk",
            domain: "domain",
            document: "document",
            title: "title",
            url: "url",
            version: "version",
            product: "product",
            keywords: ["keywords", "keywords"],
            authed: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .patch("/document/domain/document_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.document.updateDocument("domain", "document_id", {
            document: undefined,
            chunk: undefined,
            title: undefined,
            url: undefined,
            version: undefined,
            product: undefined,
            keywords: undefined,
            authed: undefined,
        });
        expect(response).toEqual({
            document_id: "document_id",
            chunk: "chunk",
            domain: "domain",
            document: "document",
            title: "title",
            url: "url",
            version: "version",
            product: "product",
            keywords: ["keywords", "keywords"],
            authed: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("deleteDocumentById", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/document/domain/document_id").respondWith().statusCode(200).build();

        const response = await client.document.deleteDocumentById("domain", "document_id");
        expect(response).toEqual(undefined);
    });

    test("getDocumentById", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            document_id: "document_id",
            chunk: "chunk",
            domain: "domain",
            document: "document",
            title: "title",
            url: "url",
            version: "version",
            product: "product",
            keywords: ["keywords", "keywords"],
            authed: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/document/domain/document_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.document.getDocumentById("domain", "document_id");
        expect(response).toEqual({
            document_id: "document_id",
            chunk: "chunk",
            domain: "domain",
            document: "document",
            title: "title",
            url: "url",
            version: "version",
            product: "product",
            keywords: ["keywords", "keywords"],
            authed: true,
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("getDocuments", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            documents: [
                {
                    document_id: "document_id",
                    chunk: "chunk",
                    domain: "domain",
                    document: "document",
                    title: "title",
                    url: "url",
                    version: "version",
                    product: "product",
                    keywords: ["keywords", "keywords"],
                    authed: true,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    document_id: "document_id",
                    chunk: "chunk",
                    domain: "domain",
                    document: "document",
                    title: "title",
                    url: "url",
                    version: "version",
                    product: "product",
                    keywords: ["keywords", "keywords"],
                    authed: true,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { total: 1, page: 1, limit: 1 },
        };
        server.mockEndpoint().get("/document/domain").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.document.getDocuments("domain");
        expect(response).toEqual({
            documents: [
                {
                    document_id: "document_id",
                    chunk: "chunk",
                    domain: "domain",
                    document: "document",
                    title: "title",
                    url: "url",
                    version: "version",
                    product: "product",
                    keywords: ["keywords", "keywords"],
                    authed: true,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    document_id: "document_id",
                    chunk: "chunk",
                    domain: "domain",
                    document: "document",
                    title: "title",
                    url: "url",
                    version: "version",
                    product: "product",
                    keywords: ["keywords", "keywords"],
                    authed: true,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: {
                total: 1,
                page: 1,
                limit: 1,
            },
        });
    });
});
