/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Guidance", () => {
    test("createGuidance", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { context: ["context", "context"], document: "document" };
        const rawResponseBody = { guidance_id: "guidance_id" };
        server
            .mockEndpoint()
            .post("/guidance/domain/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.guidance.createGuidance("domain", {
            context: ["context", "context"],
            document: "document",
        });
        expect(response).toEqual({
            guidance_id: "guidance_id",
        });
    });

    test("updateGuidanceById", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = { context: undefined, document: undefined };
        const rawResponseBody = {
            guidance_id: "guidance_id",
            context: ["context", "context"],
            domain: "domain",
            document: "document",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .patch("/guidance/domain/guidance_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.guidance.updateGuidanceById("domain", "guidance_id", {
            context: undefined,
            document: undefined,
        });
        expect(response).toEqual({
            guidance_id: "guidance_id",
            context: ["context", "context"],
            domain: "domain",
            document: "document",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("deleteGuidanceById", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/guidance/domain/guidance_id").respondWith().statusCode(200).build();

        const response = await client.guidance.deleteGuidanceById("domain", "guidance_id");
        expect(response).toEqual(undefined);
    });

    test("getGuidanceById", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            guidance_id: "guidance_id",
            context: ["context", "context"],
            domain: "domain",
            document: "document",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/guidance/domain/guidance_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.guidance.getGuidanceById("domain", "guidance_id");
        expect(response).toEqual({
            guidance_id: "guidance_id",
            context: ["context", "context"],
            domain: "domain",
            document: "document",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("getGuidances", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            guidances: [
                {
                    guidance_id: "guidance_id",
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    guidance_id: "guidance_id",
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { total: 1, page: 1, limit: 1 },
        };
        server.mockEndpoint().get("/guidance/domain").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.guidance.getGuidances("domain");
        expect(response).toEqual({
            guidances: [
                {
                    guidance_id: "guidance_id",
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    guidance_id: "guidance_id",
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: {
                total: 1,
                page: 1,
                limit: 1,
            },
        });
    });
});
