/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Index", () => {
    test("indexDocument", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            index_name: undefined,
            document_id: "document_id",
            context: ["context", "context"],
            document: "document",
        };

        server.mockEndpoint().post("/index/domain").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.index.indexDocument("domain", {
            index_name: undefined,
            document_id: "document_id",
            context: ["context", "context"],
            document: "document",
        });
        expect(response).toEqual(undefined);
    });

    test("getDocumentById", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/index/domain").respondWith().statusCode(200).build();

        const response = await client.index.getDocumentById("domain", {
            document_id: "document_id",
        });
        expect(response).toEqual(undefined);
    });

    test("updateDocument", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            document_id: "document_id",
            is_active: true,
            context: ["context", "context"],
            domain: "domain",
            document: "document",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/index/domain/update")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.index.updateDocument("domain", {
            document_id: "document_id",
            is_active: true,
            context: ["context", "context"],
            document: "document",
        });
        expect(response).toEqual({
            document_id: "document_id",
            is_active: true,
            context: ["context", "context"],
            domain: "domain",
            document: "document",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("getDocuments", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            documents: [
                {
                    document_id: "document_id",
                    is_active: true,
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    document_id: "document_id",
                    is_active: true,
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: { total: 1, page: 1, limit: 1 },
        };
        server.mockEndpoint().get("/index/domain").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.index.getDocuments("domain");
        expect(response).toEqual({
            documents: [
                {
                    document_id: "document_id",
                    is_active: true,
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
                {
                    document_id: "document_id",
                    is_active: true,
                    context: ["context", "context"],
                    domain: "domain",
                    document: "document",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            pagination: {
                total: 1,
                page: 1,
                limit: 1,
            },
        });
    });

    test("syncToQueryIndex", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/index/domain/sync").respondWith().statusCode(200).build();

        const response = await client.index.syncToQueryIndex("domain", {
            index_name: "index_name",
        });
        expect(response).toEqual(undefined);
    });
});
