/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Queries", () => {
    test("createQuery", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            query_id: "query_id",
            conversation_id: "conversation_id",
            domain: "domain",
            text: "text",
            role: "role",
            source: "source",
            created_at: "2024-01-15T09:30:00Z",
            time_to_first_token: undefined,
        };

        server.mockEndpoint().post("/queries").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.queries.createQuery({
            query_id: "query_id",
            conversation_id: "conversation_id",
            domain: "domain",
            text: "text",
            role: "role",
            source: "source",
            created_at: "2024-01-15T09:30:00Z",
            time_to_first_token: undefined,
        });
        expect(response).toEqual(undefined);
    });

    test("getRecentQueries", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            queries: [
                {
                    query_id: "query_id",
                    conversation_id: "conversation_id",
                    domain: "domain",
                    text: "text",
                    role: "role",
                    source: "source",
                    created_at: "2024-01-15T09:30:00Z",
                    time_to_first_token: 1.1,
                },
                {
                    query_id: "query_id",
                    conversation_id: "conversation_id",
                    domain: "domain",
                    text: "text",
                    role: "role",
                    source: "source",
                    created_at: "2024-01-15T09:30:00Z",
                    time_to_first_token: 1.1,
                },
            ],
            total: 1,
        };
        server.mockEndpoint().get("/queries/domain").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.queries.getRecentQueries("domain");
        expect(response).toEqual({
            queries: [
                {
                    query_id: "query_id",
                    conversation_id: "conversation_id",
                    domain: "domain",
                    text: "text",
                    role: "role",
                    source: "source",
                    created_at: "2024-01-15T09:30:00Z",
                    time_to_first_token: 1.1,
                },
                {
                    query_id: "query_id",
                    conversation_id: "conversation_id",
                    domain: "domain",
                    text: "text",
                    role: "role",
                    source: "source",
                    created_at: "2024-01-15T09:30:00Z",
                    time_to_first_token: 1.1,
                },
            ],
            total: 1,
        });
    });
});
