/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChatMessage {
    role: ChatMessage.Role;
    content: string;
}

export namespace ChatMessage {
    export type Role = "user" | "assistant";
    export const Role = {
        User: "user",
        Assistant: "assistant"
    } as const;
}
