/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface Conversation {
    conversation_id: string;
    created_at: string;
    turns: FernAI.ConversationTurn[];
}
