/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface ConversationTurn {
    role: string;
    text: string;
    created_at: string;
    feedback?: FernAI.ConversationTurnFeedback;
}
