/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateDocumentResponse {
    /** The unique identifier of the created document */
    document_id: string;
}
