/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateGuidanceResponse {
    /** The unique identifier of the created guidance document */
    guidance_id: string;
}
