/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetConversationResponse {
    /** The complete conversation with all turns */
    conversation: FernAI.Conversation;
}
