/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetDocumentsResponse {
    /** List of documents for the domain */
    documents: FernAI.Document[];
    /** Pagination information for the document list */
    pagination: FernAI.PaginationResponse;
}
