/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetHistogramAnalyticsResponse {
    /** List of histogram analytics bars */
    bars: FernAI.HistogramAnalyticsBar[];
}
