/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetInsightsResponse {
    /** List of insights with query counts */
    insights: FernAI.InsightWithMetadata[];
}
