/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMcpSemanticQueryResponse {
    /** A list of documents that are semantically relevant to the query */
    documents: string[];
}
