/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMcpBmfQueryResponse {
    /** A list of documents that are relevant to the keyword */
    documents: string[];
}
