/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetQueriesResponse {
    /** List of queries matching the request criteria */
    queries: FernAI.Query[];
    /** Pagination information */
    pagination: FernAI.PaginationResponse;
}
