/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GroupBy = "DAY" | "WEEK" | "MONTH";
export const GroupBy = {
    Day: "DAY",
    Week: "WEEK",
    Month: "MONTH",
} as const;
