/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Guidance {
    domain: string;
    context: string[];
    document: string;
    guidance_id: string;
    created_at: string;
    updated_at: string;
}
