/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface JobStatusResponse {
    /** The job ID */
    job_id: string;
    /** Current status of the job */
    status: string;
    /** When the job was created */
    created_at: string;
    /** When the job started */
    started_at?: string;
    /** When the job completed */
    completed_at?: string;
    /** Whether the job succeeded (only set when completed) */
    success?: boolean;
    /** Error message if the job failed */
    error?: string;
}
