/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LanguageModel = "claude-4-sonnet-20250514" | "command-a-03-2025";
export const LanguageModel = {
    Claude4Sonnet20250514: "claude-4-sonnet-20250514",
    CommandA032025: "command-a-03-2025",
} as const;
