/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface PostChatCompletionResponse {
    /** The conversation turns in the chat completion */
    turns: FernAI.ChatMessage[];
    /** List of citation strings */
    citations: string[];
}
