/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ReconstructIndexResponse {
    /** Whether the query index reconstruction was successful */
    success: boolean;
}
