# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .chat_completion_request import ChatCompletionRequest
from .service import AbstractChatService

__all__ = ["AbstractChatService", "ChatCompletionRequest"]
