# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..types.chat_turn import ChatTurn
from ..types.language_model import LanguageModel


class ChatCompletionRequest(UniversalBaseModel):
    model: LanguageModel = pydantic.Field()
    """
    The model to use for the chat completion.
    """

    system_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    The system prompt to use for the chat completion.
    """

    messages: typing.List[ChatTurn] = pydantic.Field()
    """
    The messages to use for the chat completion.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
