# This file was auto-generated by Fern from our API Definition.

import abc
import functools
import inspect
import logging
import typing

import fastapi
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ...commons.errors.bad_request_error import BadRequestError
from ...commons.errors.internal_error import InternalError
from ..types.chat_completion_response import ChatCompletionResponse
from .chat_completion_request import ChatCompletionRequest


class AbstractChatService(AbstractFernService):
    """
    AbstractChatService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def chat_completion(self, *, body: ChatCompletionRequest, domain: str) -> ChatCompletionResponse:
        """
        Create a docs chat completion for a given domain
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_chat_completion(router=router)

    @classmethod
    def __init_chat_completion(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.chat_completion)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.chat_completion, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.chat_completion)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> ChatCompletionResponse:
            try:
                return cls.chat_completion(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'chat_completion' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.chat_completion.__globals__)

        router.post(
            path="/chat/{domain}",
            response_model=ChatCompletionResponse,
            description=AbstractChatService.chat_completion.__doc__,
            **get_route_args(cls.chat_completion, default_tag="chat"),
        )(wrapper)
