# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ConversationSource(str, enum.Enum):
    CHAT = "CHAT"
    MCP = "MCP"

    def visit(self, chat: typing.Callable[[], T_Result], mcp: typing.Callable[[], T_Result]) -> T_Result:
        if self is ConversationSource.CHAT:
            return chat()
        if self is ConversationSource.MCP:
            return mcp()
