export const GrayscaleColor = {
    Gray: "gray",
    Mauve: "mauve",
    Slate: "slate",
    Sage: "sage",
    Olive: "olive",
    Sand: "sand",
};
export const RadixColor = {
    Tomato: "tomato",
    Red: "red",
    Ruby: "ruby",
    Crimson: "crimson",
    Pink: "pink",
    Plum: "plum",
    Purple: "purple",
    Violet: "violet",
    Iris: "iris",
    Indigo: "indigo",
    Blue: "blue",
    Cyan: "cyan",
    Teal: "teal",
    Jade: "jade",
    Green: "green",
    Grass: "grass",
    Bronze: "bronze",
    Gold: "gold",
    Brown: "brown",
    Orange: "orange",
    Amber: "amber",
    Yellow: "yellow",
    Lime: "lime",
    Mint: "mint",
    Sky: "sky",
};
export const RadixColorOrder = [
    RadixColor.Tomato,
    RadixColor.Red,
    RadixColor.Ruby,
    RadixColor.Crimson,
    RadixColor.Pink,
    RadixColor.Plum,
    RadixColor.Purple,
    RadixColor.Violet,
    RadixColor.Iris,
    RadixColor.Indigo,
    RadixColor.Blue,
    RadixColor.Cyan,
    RadixColor.Teal,
    RadixColor.Jade,
    RadixColor.Green,
    RadixColor.Grass,
    RadixColor.Bronze,
    RadixColor.Gold,
    RadixColor.Brown,
    RadixColor.Orange,
    RadixColor.Amber,
    RadixColor.Yellow,
    RadixColor.Lime,
    RadixColor.Mint,
    RadixColor.Sky,
];
export const UIColor = {
    ...RadixColor,
    Gray: "gray",
    Accent: "accent",
};
export const UIColorOrder = ["gray", "accent", ...RadixColorOrder];
export const SemanticColor = {
    Error: "error",
    Danger: "danger",
    Success: "success",
    Warning: "warning",
    Info: "info",
    None: "none",
    Primary: "primary",
};
export const SemanticColorOrder = [
    SemanticColor.Info,
    SemanticColor.Success,
    SemanticColor.Warning,
    SemanticColor.Danger,
    SemanticColor.Error,
    SemanticColor.None,
    SemanticColor.Primary,
];
export const SemanticColorMap = {
    error: "red",
    danger: "red",
    success: "green",
    warning: "amber",
    info: "blue",
    none: "gray",
    primary: "accent",
};
