# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IndexGuidanceRequest(UniversalBaseModel):
    context: typing.List[str] = pydantic.Field()
    """
    The context of the guidance document, as a list of strings, that will be indexed.
    Each string will be vectorized separately to generate a separate record.
    """

    document: str = pydantic.Field()
    """
    The content of the guidance document that will be returned to Ask Fern during Ask Fern retrieval.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
