# This file was auto-generated by Fern from our API Definition.

import abc
import functools
import inspect
import logging
import typing

import fastapi
import starlette
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ...commons.errors.bad_request_error import BadRequestError
from ...commons.errors.internal_error import InternalError
from ..types.guidance import Guidance
from ..types.guidance_id_response import GuidanceIdResponse
from ..types.guidance_list import GuidanceList
from .index_guidance_request import IndexGuidanceRequest
from .update_guidance_request import UpdateGuidanceRequest


class AbstractGuidanceService(AbstractFernService):
    """
    AbstractGuidanceService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def create_guidance(self, *, body: IndexGuidanceRequest, domain: str) -> GuidanceIdResponse:
        """
        Index a guidance document for a given domain
        """
        ...

    @abc.abstractmethod
    def update_guidance_by_id(self, *, body: UpdateGuidanceRequest, domain: str, guidance_id: str) -> Guidance:
        """
        Update a guidance document for a given domain
        """
        ...

    @abc.abstractmethod
    def delete_guidance_by_id(self, *, domain: str, guidance_id: str) -> None:
        """
        Delete a guidance document for a given domain
        """
        ...

    @abc.abstractmethod
    def get_guidance_by_id(self, *, domain: str, guidance_id: str) -> Guidance:
        """
        Get a guidance document for a given domain
        """
        ...

    @abc.abstractmethod
    def get_guidances(
        self, *, domain: str, page: typing.Optional[int] = None, limit: typing.Optional[int] = None
    ) -> GuidanceList:
        """
        Retrieve all paginated guidance documents for a given domain
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_create_guidance(router=router)
        cls.__init_update_guidance_by_id(router=router)
        cls.__init_delete_guidance_by_id(router=router)
        cls.__init_get_guidance_by_id(router=router)
        cls.__init_get_guidances(router=router)

    @classmethod
    def __init_create_guidance(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.create_guidance)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.create_guidance, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.create_guidance)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> GuidanceIdResponse:
            try:
                return cls.create_guidance(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'create_guidance' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.create_guidance.__globals__)

        router.post(
            path="/guidance/{domain}/create",
            response_model=GuidanceIdResponse,
            description=AbstractGuidanceService.create_guidance.__doc__,
            **get_route_args(cls.create_guidance, default_tag="guidance"),
        )(wrapper)

    @classmethod
    def __init_update_guidance_by_id(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.update_guidance_by_id)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "guidance_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.update_guidance_by_id, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.update_guidance_by_id)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Guidance:
            try:
                return cls.update_guidance_by_id(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'update_guidance_by_id' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.update_guidance_by_id.__globals__)

        router.patch(
            path="/guidance/{domain}/{guidance_id}",
            response_model=Guidance,
            description=AbstractGuidanceService.update_guidance_by_id.__doc__,
            **get_route_args(cls.update_guidance_by_id, default_tag="guidance"),
        )(wrapper)

    @classmethod
    def __init_delete_guidance_by_id(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.delete_guidance_by_id)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "guidance_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.delete_guidance_by_id, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.delete_guidance_by_id)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> None:
            try:
                return cls.delete_guidance_by_id(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'delete_guidance_by_id' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.delete_guidance_by_id.__globals__)

        router.delete(
            path="/guidance/{domain}/{guidance_id}",
            response_model=None,
            status_code=starlette.status.HTTP_204_NO_CONTENT,
            description=AbstractGuidanceService.delete_guidance_by_id.__doc__,
            **get_route_args(cls.delete_guidance_by_id, default_tag="guidance"),
        )(wrapper)

    @classmethod
    def __init_get_guidance_by_id(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_guidance_by_id)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "guidance_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.get_guidance_by_id, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_guidance_by_id)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> Guidance:
            try:
                return cls.get_guidance_by_id(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_guidance_by_id' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_guidance_by_id.__globals__)

        router.get(
            path="/guidance/{domain}/{guidance_id}",
            response_model=Guidance,
            description=AbstractGuidanceService.get_guidance_by_id.__doc__,
            **get_route_args(cls.get_guidance_by_id, default_tag="guidance"),
        )(wrapper)

    @classmethod
    def __init_get_guidances(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_guidances)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "page":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            elif parameter_name == "limit":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            else:
                new_parameters.append(parameter)
        setattr(cls.get_guidances, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_guidances)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> GuidanceList:
            try:
                return cls.get_guidances(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_guidances' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_guidances.__globals__)

        router.get(
            path="/guidance/{domain}",
            response_model=GuidanceList,
            description=AbstractGuidanceService.get_guidances.__doc__,
            **get_route_args(cls.get_guidances, default_tag="guidance"),
        )(wrapper)
