# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateGuidanceRequest(UniversalBaseModel):
    context: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The updated context of the guidance document, as a list of strings, that will be indexed.
    If not provided, this field will remain unchanged.
    """

    document: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated content of the guidance document that will be returned to Ask Fern during Ask Fern retrieval.
    If not provided, this field will remain unchanged.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
