/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         document: undefined,
 *         chunk: undefined,
 *         title: undefined,
 *         url: undefined,
 *         version: undefined,
 *         product: undefined,
 *         keywords: undefined,
 *         authed: undefined
 *     }
 */
export interface UpdateDocumentRequest {
    /**
     * The updated content of the document that will be returned to Ask Fern during document retrieval.
     * If not provided, this field will remain unchanged.
     */
    document?: string;
    /**
     * The updated textual content that should be vectorized when indexing the document.
     * If not provided, this field will remain unchanged.
     */
    chunk?: string;
    /** The updated title of the document. If not provided, this field will remain unchanged. */
    title?: string;
    /** The updated url of the document. If not provided, this field will remain unchanged. */
    url?: string;
    /** The updated version of the document. If not provided, this field will remain unchanged. */
    version?: string;
    /** The updated product of the document. If not provided, this field will remain unchanged. */
    product?: string;
    /** The updated keywords of the document. If not provided, this field will remain unchanged. */
    keywords?: string[];
    /** The updated authed status of the document. If not provided, this field will remain unchanged. */
    authed?: boolean;
}
