version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "0:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  fai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - IS_LOCAL=true
      - PYTHONPATH=${PYTHONPATH}:${PWD}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TURBOPUFFER_API_KEY=${TURBOPUFFER_API_KEY}
    volumes:
      - .:/app

volumes:
  pgdata:
