/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         domain: "domain",
 *         org_name: "org_name"
 *     }
 */
export interface ToggleAskAiRequest {
    domain: string;
    org_name: string;
    preview?: boolean;
}
