/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         status: 1,
 *         sourceMessageId: "sourceMessageId"
 *     }
 */
export interface UpstashCallbackRequest {
    status: number;
    sourceMessageId: string;
    url?: string;
    method?: string;
    sourceHeader?: Record<string, string[] | undefined>;
    sourceBody?: string;
    notBefore?: number;
    createdAt?: number;
    scheduleId?: string;
    callerIP?: string;
}
