/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../../../../index.js";

/**
 * @example
 *     {
 *         messages: [{
 *                 role: "user",
 *                 content: "content"
 *             }]
 *     }
 */
export interface PostChatCompletionRequest {
    /** The model to use for the chat completion */
    model?: FernAI.LanguageModel;
    /** The system prompt to use for the chat completion */
    system_prompt?: string;
    /** The messages to use for the chat completion */
    messages: FernAI.ChatMessage[];
}
