# This file was auto-generated by Fern from our API Definition.

import abc
import functools
import inspect
import logging
import typing

import fastapi
import starlette
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ...commons.errors.bad_request_error import BadRequestError
from ...commons.errors.internal_error import InternalError


class AbstractIndexService(AbstractFernService):
    """
    AbstractIndexService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def reconstruct_query_index(self, *, domain: str) -> None:
        """
        Reconstruct the query index for a given domain
        """
        ...

    @abc.abstractmethod
    def sync_to_query_index(self, *, domain: str, index_name: str) -> None:
        """
        Sync an index with the query index
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_reconstruct_query_index(router=router)
        cls.__init_sync_to_query_index(router=router)

    @classmethod
    def __init_reconstruct_query_index(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.reconstruct_query_index)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.reconstruct_query_index, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.reconstruct_query_index)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> None:
            try:
                return cls.reconstruct_query_index(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'reconstruct_query_index' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.reconstruct_query_index.__globals__)

        router.post(
            path="/index/{domain}/reconstruct",
            response_model=None,
            status_code=starlette.status.HTTP_204_NO_CONTENT,
            description=AbstractIndexService.reconstruct_query_index.__doc__,
            **get_route_args(cls.reconstruct_query_index, default_tag="index"),
        )(wrapper)

    @classmethod
    def __init_sync_to_query_index(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.sync_to_query_index)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "index_name":
                new_parameters.append(
                    parameter.replace(default=fastapi.Query(default=..., description="The name of the index to sync"))
                )
            else:
                new_parameters.append(parameter)
        setattr(cls.sync_to_query_index, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.sync_to_query_index)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> None:
            try:
                return cls.sync_to_query_index(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'sync_to_query_index' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.sync_to_query_index.__globals__)

        router.post(
            path="/index/{domain}/sync",
            response_model=None,
            status_code=starlette.status.HTTP_204_NO_CONTENT,
            description=AbstractIndexService.sync_to_query_index.__doc__,
            **get_route_args(cls.sync_to_query_index, default_tag="index"),
        )(wrapper)
