/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         keywords: "keywords"
 *     }
 */
export interface GetMcpBmfQueryRequest {
    /** The bm25 keywords to get the documents for */
    keywords: string;
}
