/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         semantic_query: "semantic_query"
 *     }
 */
export interface GetMcpSemanticQueryRequest {
    /** The semantic query to get the documents for */
    semantic_query: string;
}
