# This file was auto-generated by Fern from our API Definition.

import abc
import datetime as dt
import functools
import inspect
import logging
import typing

import fastapi
import starlette
from ....core.abstract_fern_service import AbstractFernService
from ....core.exceptions.fern_http_exception import FernHTTPException
from ....core.route_args import get_route_args
from ...commons.errors.bad_request_error import BadRequestError
from ...commons.errors.internal_error import InternalError
from ..types.query_page import QueryPage
from .create_query_request import CreateQueryRequest


class AbstractQueriesService(AbstractFernService):
    """
    AbstractQueriesService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def create_query(self, *, body: CreateQueryRequest) -> None:
        """
        Log a new query to the FAI DB
        """
        ...

    @abc.abstractmethod
    def get_recent_queries(
        self,
        *,
        domain: str,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        cutoff_time: typing.Optional[dt.datetime] = None,
        include_assistant: typing.Optional[bool] = None,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
    ) -> QueryPage:
        """
        Retrieve all paginated recent queries
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_create_query(router=router)
        cls.__init_get_recent_queries(router=router)

    @classmethod
    def __init_create_query(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.create_query)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "body":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            else:
                new_parameters.append(parameter)
        setattr(cls.create_query, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.create_query)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> None:
            try:
                return cls.create_query(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'create_query' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.create_query.__globals__)

        router.post(
            path="/queries",
            response_model=None,
            status_code=starlette.status.HTTP_204_NO_CONTENT,
            description=AbstractQueriesService.create_query.__doc__,
            **get_route_args(cls.create_query, default_tag="queries"),
        )(wrapper)

    @classmethod
    def __init_get_recent_queries(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.get_recent_queries)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(endpoint_function.parameters.items()):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "domain":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "page":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            elif parameter_name == "limit":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            elif parameter_name == "cutoff_time":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            elif parameter_name == "include_assistant":
                new_parameters.append(parameter.replace(default=fastapi.Query(default=None)))
            elif parameter_name == "start_date":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=None, description="The start date of the period to retrieve analytics for"
                        )
                    )
                )
            elif parameter_name == "end_date":
                new_parameters.append(
                    parameter.replace(
                        default=fastapi.Query(
                            default=None, description="The end date of the period to retrieve analytics for"
                        )
                    )
                )
            else:
                new_parameters.append(parameter)
        setattr(cls.get_recent_queries, "__signature__", endpoint_function.replace(parameters=new_parameters))

        @functools.wraps(cls.get_recent_queries)
        def wrapper(*args: typing.Any, **kwargs: typing.Any) -> QueryPage:
            try:
                return cls.get_recent_queries(*args, **kwargs)
            except (BadRequestError, InternalError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'get_recent_queries' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.get_recent_queries.__globals__)

        router.get(
            path="/queries/{domain}",
            response_model=QueryPage,
            description=AbstractQueriesService.get_recent_queries.__doc__,
            **get_route_args(cls.get_recent_queries, default_tag="queries"),
        )(wrapper)
