name: Test Containers

on:
  push:
    branches:
      - app
  pull_request:
    paths:
      - "servers/fdr/**"
      - "servers/mdx-bundler/**"
      - ".github/workflows/container-testing.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/app' }}

jobs:
  fdr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install
        uses: ./.github/actions/install

      - name: Build container
        run: docker build -f servers/fdr/Dockerfile -t fern-definition-registry:local --build-arg DATABASE_URL='postgres://fdr:fdr1!@postgres:5432/postgres' .

      - name: Standup test cluster
        run: docker compose -f servers/fdr/docker-compose.ete.yml up -d --wait

      - name: Run tests
        run: pnpm --filter=@fern-platform/fdr test:ete --run

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::985111089818:role/github-ci"
          aws-region: "us-east-1"

      - name: Push to ECR for scanning
        run: |-
          aws sts get-caller-identity
          SANITIZED_BRANCH="${BRANCH_NAME//\//-}"
          docker tag fern-definition-registry:local 985111089818.dkr.ecr.us-east-1.amazonaws.com/dev/fdr-internal:$SANITIZED_BRANCH-${{ github.sha }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 985111089818.dkr.ecr.us-east-1.amazonaws.com
          docker push 985111089818.dkr.ecr.us-east-1.amazonaws.com/dev/fdr-internal:$SANITIZED_BRANCH-${{ github.sha }}

    # Cleanup needed locally but not in CI
    # - name: cleanup
    #   run: docker compose -f servers/fdr/docker-compose.ete.yml down -v

  mdx-bundler:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install
        uses: ./.github/actions/install

      - name: run build:tsup:cjs
        run: |
          pnpm build
          pnpm --filter @fern-platform/mdx-bundler run build:tsup:cjs

      - name: Build container
        run: docker build -f servers/mdx-bundler/Dockerfile -t mdx-bundler:local .

      - name: Standup test container
        run: docker compose -f servers/mdx-bundler/docker-compose.yml up -d --wait

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::985111089818:role/github-ci"
          aws-region: "us-east-1"

      - name: Push to ECR for scanning
        run: |-
          aws sts get-caller-identity
          SANITIZED_BRANCH="${BRANCH_NAME//\//-}"
          docker tag mdx-bundler:local 985111089818.dkr.ecr.us-east-1.amazonaws.com/dev/mdx-bundler-internal:$SANITIZED_BRANCH-${{ github.sha }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 985111089818.dkr.ecr.us-east-1.amazonaws.com
          docker push 985111089818.dkr.ecr.us-east-1.amazonaws.com/dev/mdx-bundler-internal:$SANITIZED_BRANCH-${{ github.sha }}
