name: FernAI - Test and Deploy

on:
  push:
    branches:
      - "**"
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Fern Dev
    env:
      TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      POSTGRES_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/mydatabase
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1
          cd servers/fai
          poetry install
      - name: Create .env file
        run: |
          cd servers/fai
          echo "TURBOPUFFER_API_KEY=${{ env.TURBOPUFFER_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" >> .env
          echo "POSTGRES_DATABASE_URL=${{ env.POSTGRES_DATABASE_URL }}" >> .env
      - name: test
        run: |
          cd servers/fai
          poetry run pytest -sv

  deploy-dev2:
    if: github.ref == 'refs/heads/app'
    needs:
      - test
    runs-on: ubuntu-latest
    environment: Fern Dev
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
      POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create .env file
        run: |
          cd servers/fai
          echo "TURBOPUFFER_API_KEY=${{ env.TURBOPUFFER_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" >> .env
          echo "POSTGRES_DATABASE_URL=${{ env.POSTGRES_DATABASE_URL }}" >> .env
      - name: Deploy to Dev
        run: |
          git_version="$(scripts/fai-version.sh)"
          cd servers/fai
          ./scripts/create_docker.sh "${git_version}"
          cd deploy
          npm install
          VERSION="${git_version}" npm run cdk deploy fai-dev2 --require-approval never --progress events

  deploy-prod:
    if: contains(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-latest
    environment: Fern Prod
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
      POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create .env file
        run: |
          cd servers/fai
          echo "TURBOPUFFER_API_KEY=${{ env.TURBOPUFFER_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" >> .env
          echo "POSTGRES_DATABASE_URL=${{ env.POSTGRES_DATABASE_URL }}" >> .env
      - name: Deploy to prod
        run: |
          git_version="$(scripts/fai-version.sh)"
          cd servers/fai
          ./scripts/create_docker.sh "${git_version}"
          cd deploy
          npm install
          VERSION="${git_version}" npm run cdk deploy fai-prod --require-approval never --progress events
