name: 'Rebase stable from app'
on:
  schedule:
    - cron: '0 12 * * MON'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: stable
          fetch-depth: 0
          token: ${{ secrets.PR_BOT_GH_PAT }}


      - name: Rebase
        run: |
          git fetch origin app
          git rebase origin/app

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.PR_BOT_GH_PAT }}
        run: git push --force-with-lease origin stable