name: CI

on:
  push:
    branches:
      - app
  pull_request:

jobs:
  run-self-hosted-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # This helps turbo resolve changes faster

      - name: Install
        uses: ./.github/actions/install

      - name: Compile and build
        run: pnpm turbo compile codegen build
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          WORKOS_API_KEY: ${{ secrets.WORKOS_API_KEY }}
          WORKOS_CLIENT_ID: ${{ secrets.WORKOS_CLIENT_ID }}

      - name: Build FDR CJS
        run: pnpm --filter @fern-platform/fdr build:tsup:cjs          
        
      - name: Build docs bundle
        run: pnpm docs:self-hosted-bundle:build

      - name: Next.js Cache Init
        uses: ./.github/actions/next-cache

      - name: Run tests
        run: pnpm turbo build test:self-hosted --filter=@fern-platform/self-hosted
