name: Check Sites

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  get-sites:
    name: Determine sites to check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Log location info
        run: curl ipinfo.io
      - uses: actions/checkout@v4
      - name: Update domain list
        env:
          VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: python get_sites.py
      - name: Upload domain list
        uses: actions/upload-artifact@v4
        with:
          name: Domains
          path: sites.csv

  up:
    name: Check if sites are up (US)
    runs-on: ubuntu-latest
    needs: get-sites
    timeout-minutes: 10
    steps:
      - name: Log location info
        run: curl ipinfo.io
      - uses: actions/checkout@v4
      - name: Download domain list
        uses: actions/download-artifact@v4
        with:
          name: Domains
      - name: PWD & LS
        run: |
          pwd
          ls
      - name: Check Sites
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
        run: python check_sites.py US

  up-eu:
    needs: up
    if: always()
    name: Check if sites are up (via EU runner)
    runs-on:
      group: International
      labels: eu
    timeout-minutes: 10
    steps:
      - name: Log location info
        run: curl ipinfo.io
      - uses: actions/checkout@v4
      - name: Download domain list
        uses: actions/download-artifact@v4
        with:
          name: Domains
      - name: Check Sites
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
        run: python check_sites.py EU