name: Check Sites

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test-syntax:
    runs-on: Seed
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # This helps turbo resolve changes faster
      - name: Install
        uses: ./.github/actions/install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install Prisma CLI
        run: npm install --global prisma@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
