/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as core from "../../../../core/index.js";
import type * as environments from "../../../../environments.js";
import { V2 } from "../resources/v2/client/Client.js";

export declare namespace Docs {
    export interface Options {
        environment?: core.Supplier<environments.FdrLambdaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Docs {
    protected readonly _options: Docs.Options;
    protected _v2: V2 | undefined;

    constructor(_options: Docs.Options) {
        this._options = _options;
    }

    public get v2(): V2 {
        return (this._v2 ??= new V2(this._options));
    }
}
