"use client";

import React, {
  ComponentProps,
  ReactElement,
  useEffect,
  useRef,
  useState,
} from "react";

import { Check, Link2 } from "lucide-react";
import { AnimatePresence, LazyMotion, domAnimation } from "motion/react";
import * as m from "motion/react-m";

import { cn } from "@fern-docs/components";
import { FernLink } from "@fern-docs/components/FernLink";
import { useCopyToClipboard } from "@fern-ui/react-commons";

import { useEditorComponent } from "@/components/editor/editor-component/EditorComponentContext";
import {
  EditorComponentPopoverButton,
  EditorComponentPopoverProvider,
} from "@/components/editor/editor-component/EditorComponentPopover";
import {
  CheckboxControl,
  TextInputControl,
} from "@/components/editor/editor-component/controls";
import { useIsFernAnchorDisabled } from "@/docs/components/FernAnchor";

import { useStepsContext } from "./Steps";

interface StepProps extends ComponentProps<"div"> {
  id: string; // id can be overridden, but a default is generated by rehypeSteps
  title?: string;
  toc?: boolean;
}

export function Step({
  children,
  className,
  title,
  id,
  toc = false,
  ...props
}: StepProps): ReactElement<any> {
  const { registerStep, unregisterStep, getStepIndex, steps } =
    useStepsContext();
  const { isWithinEditor } = useEditorComponent();
  const uniqueId = React.useId();
  const stepId = id || `step-${uniqueId}`;
  const index = getStepIndex(stepId);
  const href = `#${stepId}`;
  const { copyToClipboard, wasJustCopied } = useCopyToClipboard(() =>
    new URL(href, window.location.href).toString()
  );
  const [hover, setHover] = useState(false);
  const isFernAnchorDisabled = useIsFernAnchorDisabled();
  const stepRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    registerStep({
      id: stepId,
      title,
    });

    return () => {
      unregisterStep(stepId);
    };
  }, [stepId, title, registerStep, unregisterStep]);

  const stepContent = (
    <div
      ref={stepRef}
      className={cn("fern-step", className)}
      id={stepId}
      {...props}
    >
      {isWithinEditor && (
        <EditorComponentPopoverButton
          className="absolute right-2 top-0"
          disableDelete={steps.length === 1}
        />
      )}
      {!isFernAnchorDisabled && (
        <FernLink
          className="fern-anchor"
          href={href}
          shallow={true}
          scroll={false}
          replace={true}
          onClick={() => void copyToClipboard?.()}
          onPointerEnter={() => setHover(true)}
          onPointerLeave={() => setHover(false)}
          tabIndex={-1}
        >
          <span className="fern-anchor-icon">
            {hover ? <Link2 /> : <span>{index}</span>}
          </span>
          <LazyMotion features={domAnimation}>
            <AnimatePresence>
              {wasJustCopied && (
                <m.div
                  className="fern-anchor-icon copied"
                  exit={{ opacity: 0 }}
                >
                  <Check />
                </m.div>
              )}
            </AnimatePresence>
          </LazyMotion>
        </FernLink>
      )}
      {title != null && (
        <h3
          onPointerEnter={() => setHover(true)}
          onPointerLeave={() => setHover(false)}
        >
          {title}
        </h3>
      )}
      {isWithinEditor ? (
        <div className="solid-hover-handle -ml-8 -mt-2">{children}</div>
      ) : (
        <>{children}</>
      )}
    </div>
  );

  if (isWithinEditor) {
    return (
      <EditorComponentPopoverProvider
        attributes={{
          title: new TextInputControl({
            placeholder: "Step title",
            defaultValue: title,
          }),
          toc: new CheckboxControl({
            defaultValue: toc,
            label: "Show in table of contents",
          }),
        }}
        targetRef={stepRef}
      >
        {stepContent}
      </EditorComponentPopoverProvider>
    );
  }

  return stepContent;
}
