"use client";

import { cn } from "@fern-docs/components/cn";
import { FernLink } from "@fern-docs/components/FernLink";
import { useCopyToClipboard } from "@fern-ui/react-commons";
import { Check, Link2 } from "lucide-react";
import { AnimatePresence, domAnimation, LazyMotion } from "motion/react";
import * as m from "motion/react-m";
import React, { type ComponentProps, type ReactElement, useEffect, useRef, useState } from "react";
import { CheckboxControl, TextInputControl } from "@/components/editor/editor-component/controls";
import { useEditorComponent } from "@/components/editor/editor-component/EditorComponentContext";
import {
    EditorComponentPopoverButton,
    EditorComponentPopoverProvider
} from "@/components/editor/editor-component/EditorComponentPopover";
import { useIsFernAnchorDisabled } from "@/docs/components/FernAnchor";

import { useStepsContext } from "./Steps";

interface StepProps extends ComponentProps<"div"> {
    id: string; // id can be overridden, but a default is generated by rehypeSteps
    title?: string;
    toc?: boolean;
}

export function Step({ children, className, title, id, toc = false, ...props }: StepProps): ReactElement<any> {
    const { registerStep, unregisterStep, getStepIndex, steps } = useStepsContext();

    // Get the editor component values if we're within the editor
    const editorComponentValues = useEditorComponent();
    const { isWithinEditor } = editorComponentValues;
    const uniqueId = React.useId();
    const stepId = id || `step-${uniqueId}`;
    const index = getStepIndex(stepId);
    const href = `#${stepId}`;
    const { copyToClipboard, wasJustCopied } = useCopyToClipboard(() => new URL(href, window.location.href).toString());
    const [hover, setHover] = useState(false);
    const isFernAnchorDisabled = useIsFernAnchorDisabled();
    const stepRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        registerStep({
            id: stepId,
            title,
            // Pass the editor component values to the StepGroup
            editorComponentValues: editorComponentValues.isWithinEditor ? editorComponentValues : undefined
        });

        return () => {
            unregisterStep(stepId);
        };
    }, [stepId, title, registerStep, unregisterStep, editorComponentValues]);

    const stepContent = (
        <div ref={stepRef} className={cn("fern-step", className)} id={stepId} {...props}>
            {/* Popover button will be handled by EditorComponentPopoverProvider wrapper */}
            {!isFernAnchorDisabled && (
                <FernLink
                    className="fern-anchor"
                    href={href}
                    shallow={true}
                    scroll={false}
                    replace={true}
                    onClick={() => void copyToClipboard?.()}
                    onPointerEnter={() => setHover(true)}
                    onPointerLeave={() => setHover(false)}
                    tabIndex={-1}
                >
                    <span className="fern-anchor-icon">{hover ? <Link2 /> : <span>{index}</span>}</span>
                    <LazyMotion features={domAnimation}>
                        <AnimatePresence>
                            {wasJustCopied && (
                                <m.div className="fern-anchor-icon copied" exit={{ opacity: 0 }}>
                                    <Check />
                                </m.div>
                            )}
                        </AnimatePresence>
                    </LazyMotion>
                </FernLink>
            )}
            {title != null && (
                <h3 onPointerEnter={() => setHover(true)} onPointerLeave={() => setHover(false)}>
                    {title}
                </h3>
            )}
            {isWithinEditor ? <div className="solid-hover-handle -ml-8 -mt-2">{children}</div> : <>{children}</>}
        </div>
    );

    if (isWithinEditor) {
        return (
            <EditorComponentPopoverProvider
                attributes={{
                    title: new TextInputControl({
                        placeholder: "Step title",
                        defaultValue: title
                    }),
                    toc: new CheckboxControl({
                        defaultValue: toc,
                        label: "Show in table of contents"
                    })
                }}
                targetRef={stepRef}
            >
                <div className="relative">
                    <EditorComponentPopoverButton
                        className="absolute right-2 top-0"
                        disableDelete={steps.length === 1}
                    />
                    {stepContent}
                </div>
            </EditorComponentPopoverProvider>
        );
    }

    return stepContent;
}
